// Autogenerated code; DO NOT EDIT.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Contact: containerplat-dev@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

type Attachment struct {
	Type_                        *AttachmentType `json:"Type,omitempty"`
	Path                         string          `json:"Path,omitempty"`
	IgnoreFlushes                bool            `json:"IgnoreFlushes,omitempty"`
	CachingMode                  *CachingMode    `json:"CachingMode,omitempty"`
	NoWriteHardening             bool            `json:"NoWriteHardening,omitempty"`
	DisableExpansionOptimization bool            `json:"DisableExpansionOptimization,omitempty"`
	IgnoreRelativeLocator        bool            `json:"IgnoreRelativeLocator,omitempty"`
	CaptureIoAttributionContext  bool            `json:"CaptureIoAttributionContext,omitempty"`
	ReadOnly                     bool            `json:"ReadOnly,omitempty"`
	SupportCompressedVolumes     bool            `json:"SupportCompressedVolumes,omitempty"`
	AlwaysAllowSparseFiles       bool            `json:"AlwaysAllowSparseFiles,omitempty"`
	SupportEncryptedFiles        bool            `json:"SupportEncryptedFiles,omitempty"`
	ExtensibleVirtualDiskType    string          `json:"ExtensibleVirtualDiskType,omitempty"`
	IopsLimit                    int64           `json:"IopsLimit,omitempty"`
	IopsReservation              int64           `json:"IopsReservation,omitempty"`
	Weight                       int64           `json:"Weight,omitempty"`
	QosPolicyId                  string          `json:"QosPolicyId,omitempty"`
	WriteHardeningMethod         *WriteHardening `json:"WriteHardeningMethod,omitempty"`
}
