// Autogenerated code; DO NOT EDIT.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Contact: containerplat-dev@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

type CacheMode string

// List of CacheMode
const (
	CacheMode_EMPTY                 CacheMode = ""
	CacheMode_DISABLED              CacheMode = "Disabled"
	CacheMode_ENABLED               CacheMode = "Enabled"
	CacheMode_PRIVATE               CacheMode = "Private"
	CacheMode_PRIVATE_ALLOW_SHARING CacheMode = "PrivateAllowSharing"
)
