// Autogenerated code; DO NOT EDIT.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Contact: containerplat-dev@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

type CacheQueryStatsResponse struct {
	L3OccupancyBytes uint64 `json:"L3OccupancyBytes,omitempty"`
	L3TotalBwBytes   uint64 `json:"L3TotalBwBytes,omitempty"`
	L3LocalBwBytes   uint64 `json:"L3LocalBwBytes,omitempty"`
}
