// Autogenerated code; DO NOT EDIT.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Contact: containerplat-dev@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

// Structure to return processor cache monitoring settings for a Service property query.
type CacheMonitoringSystemInfo struct {
	L3CmtSupported                 bool                     `json:"L3CmtSupported,omitempty"`
	L3OccupancyMonitoringSupported bool                     `json:"L3OccupancyMonitoringSupported,omitempty"`
	L3TotalBwMonitoringSupported   bool                     `json:"L3TotalBwMonitoringSupported,omitempty"`
	L3LocalBwMonitoringSupported   bool                     `json:"L3LocalBwMonitoringSupported,omitempty"`
	MaxRmid                        uint32                   `json:"MaxRmid,omitempty"`
	RootRmid                       uint32                   `json:"RootRmid,omitempty"`
	RootCacheStats                 *CacheQueryStatsResponse `json:"RootCacheStats,omitempty"`
}
