// Autogenerated code; DO NOT EDIT.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Contact: containerplat-dev@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

type CachingMode string

// List of CachingMode
const (
	CachingMode_UNCACHED         CachingMode = "Uncached"
	CachingMode_CACHED           CachingMode = "Cached"
	CachingMode_READ_ONLY_CACHED CachingMode = "ReadOnlyCached"
)
