// Autogenerated code; DO NOT EDIT.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Contact: containerplat-dev@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

type Chipset struct {
	Uefi                     *Uefi                  `json:"Uefi,omitempty"`
	Pcat                     *Pcat                  `json:"Pcat,omitempty"`
	IsNumLockDisabled        bool                   `json:"IsNumLockDisabled,omitempty"`
	BaseBoardSerialNumber    string                 `json:"BaseBoardSerialNumber,omitempty"`
	ChassisSerialNumber      string                 `json:"ChassisSerialNumber,omitempty"`
	ChassisAssetTag          string                 `json:"ChassisAssetTag,omitempty"`
	EnableHibernation        bool                   `json:"EnableHibernation,omitempty"`
	UseUtc                   bool                   `json:"UseUtc,omitempty"`
	LinuxKernelDirect        *LinuxKernelDirect     `json:"LinuxKernelDirect,omitempty"`
	SystemInformation        *UefiSystemInformation `json:"SystemInformation,omitempty"`
	MemoryDeviceSerialNumber string                 `json:"MemoryDeviceSerialNumber,omitempty"`
	BiosGUID                 string                 `json:"BiosGUID,omitempty"`
	BiosSerialNumber         string                 `json:"BiosSerialNumber,omitempty"`
	// FirmwareMode is File
	IsFileFirmwareMode   bool         `json:"IsFileFirmwareMode,omitempty"`
	PxePreferredProtocol *PxeProtocol `json:"PxePreferredProtocol,omitempty"`
	BiosLockString       string       `json:"BiosLockString,omitempty"`
}
