// Autogenerated code; DO NOT EDIT.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Contact: containerplat-dev@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

// ComPort specifies the named pipe that will be used for the port, with empty string indicating a disconnected port.
type ComPort struct {
	NamedPipe           string `json:"NamedPipe,omitempty"`
	OptimizeForDebugger bool   `json:"OptimizeForDebugger,omitempty"`
	// Internal set that COM1/COM2 should be forced enable if chipset is PCAT
	ForceEnable bool `json:"ForceEnable,omitempty"`
	// Only used in VMMS VM, not sure if it needs to expose in HCS
	InputBufferSize uint32 `json:"InputBufferSize,omitempty"`
}
