// Autogenerated code; DO NOT EDIT.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Contact: containerplat-dev@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

// A query to request a screenshot of the console of the virtual machine
type ConsoleImageQuery struct {
	// Requested width of the resulting image
	Width uint16 `json:"Width,omitempty"`
	// Requested height of the resulting image
	Height uint16 `json:"Height,omitempty"`
	// Flags that determine certain characteristics of the output of the returned image 0x00000001ul: The image data is returned in the OctetString format defined by the DMTF. The first four bytes of the data contains the number of octets (bytes), including the four-byte length, in the big-endian format
	Flags uint32 `json:"Flags,omitempty"`
}
