// Autogenerated code; DO NOT EDIT.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Contact: containerplat-dev@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

// Specifies the HvSocket configurations required for a Container Credential Guard instance that is meant to be used with HvSocket transport.
type ContainerCredentialGuardHvSocketServiceConfig struct {
	// Identifier of the service that needs to be configured over HvSocket.
	ServiceId     string                 `json:"ServiceId,omitempty"`
	ServiceConfig *HvSocketServiceConfig `json:"ServiceConfig,omitempty"`
}
