// Autogenerated code; DO NOT EDIT.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Contact: containerplat-dev@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

type ContainerCredentialGuardModifyOperation string

// List of ContainerCredentialGuardModifyOperation
const (
	ContainerCredentialGuardModifyOperation_ADD_INSTANCE    ContainerCredentialGuardModifyOperation = "AddInstance"
	ContainerCredentialGuardModifyOperation_REMOVE_INSTANCE ContainerCredentialGuardModifyOperation = "RemoveInstance"
)
