// Autogenerated code; DO NOT EDIT.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Contact: containerplat-dev@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

// Describes memory configuration for a container.
type ContainerMemory struct {
	// Specifies the memory size in megabytes.
	SizeInMB uint64 `json:"SizeInMB,omitempty"`
	// TODO (beweedon 7/18/2018): Remove this once we no longer support RS4 GCS.
	Maximum uint64 `json:"Maximum,omitempty"`
}
