// Autogenerated code; DO NOT EDIT.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Contact: containerplat-dev@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

// Describes the HvSocket configuration and options for a container.
type ContainerHvSocket struct {
	Config *HvSocketSystemConfig `json:"Config,omitempty"`
	// When true, enables Powershell Direct service in the guest to allow it to use the HvSocket transport.
	EnablePowerShellDirect bool `json:"EnablePowerShellDirect,omitempty"`
	// When true, enables UTC relay in the HvSocket transport.
	EnableUtcRelay bool `json:"EnableUtcRelay,omitempty"`
	// When true, enables auditing in the HvSocket transport.
	EnableAuditing bool `json:"EnableAuditing,omitempty"`
}
