// Autogenerated code; DO NOT EDIT.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Contact: containerplat-dev@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

// Describes the configuration of a running Container Credential Guard Instance.
type ContainerCredentialGuardInstance struct {
	// Identifier of a Container Credential Guard Instance, globally unique.
	Id              string                                         `json:"Id,omitempty"`
	CredentialGuard *ContainerCredentialGuardState                 `json:"CredentialGuard,omitempty"`
	HvSocketConfig  *ContainerCredentialGuardHvSocketServiceConfig `json:"HvSocketConfig,omitempty"`
}
