// Autogenerated code; DO NOT EDIT.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Contact: containerplat-dev@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

type CpuGroupProperty struct {
	PropertyCode  uint32 `json:"PropertyCode,omitempty"`
	PropertyValue uint64 `json:"PropertyValue,omitempty"`
}
