// Autogenerated code; DO NOT EDIT.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Contact: containerplat-dev@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

// Information on a live dump. Live dumps are configured in DebugOptions.
type CrashReportLiveDump struct {
	// Name of the dump file
	DumpFile string `json:"DumpFile,omitempty"`
	// Status of the process dump. S_OK indicates success, other HRESULT values on error.
	Status int32 `json:"Status,omitempty"`
	// User pages were requested and included in the live dump.
	UserPagesAvailable bool `json:"UserPagesAvailable,omitempty"`
}
