// Autogenerated code; DO NOT EDIT.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Contact: containerplat-dev@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

type DebugOptions struct {
	// Capture a save state to the given file if the guest crashes.
	BugcheckSavedStateFileName string `json:"BugcheckSavedStateFileName,omitempty"`
	// Capture a save state to the given file if the guest crashes and no crash dump can be written.
	BugcheckNoCrashdumpSavedStateFileName string `json:"BugcheckNoCrashdumpSavedStateFileName,omitempty"`
	// Capture a save state to the given file if the guest triple faults.
	TripleFaultSavedStateFileName string `json:"TripleFaultSavedStateFileName,omitempty"`
	// Name of a dump file to use for firmware crashes.
	FirmwareDumpFileName          string       `json:"FirmwareDumpFileName,omitempty"`
	WorkerProcessDumpOnGuestCrash *ProcessDump `json:"WorkerProcessDumpOnGuestCrash,omitempty"`
	LiveDumpOnGuestCrash          *LiveDump    `json:"LiveDumpOnGuestCrash,omitempty"`
}
