// Autogenerated code; DO NOT EDIT.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Contact: containerplat-dev@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

type DeviceType string

// List of DeviceType
const (
	DeviceType_CLASS_GUID      DeviceType = "ClassGuid"
	DeviceType_DEVICE_INSTANCE DeviceType = "DeviceInstance"
	DeviceType_GPU_MIRROR      DeviceType = "GpuMirror"
)
