// Autogenerated code; DO NOT EDIT.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Contact: containerplat-dev@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

type EmulatedNetworkAdapter struct {
	MacAddress  string       `json:"MacAddress,omitempty"`
	IovSettings *IovSettings `json:"IovSettings,omitempty"`
	// Identification of the connected switch
	SwitchId string `json:"SwitchId,omitempty"`
	// Identification of the connected port that is part of the switch
	PortId string `json:"PortId,omitempty"`
	// Name of the switch
	SwitchName string `json:"SwitchName,omitempty"`
	// Whether the switch port used by this network adapter is configured to persist across reboots, used to support legacy scenarios. Persistent ports are heavier-weight than transient ports, which are cleaned up on host exit.
	UsePersistentPort bool `json:"UsePersistentPort,omitempty"`
	// The resource pool ID associated with this network adapter, used to report network metrics aggregated by that resource pool.
	ResourcePoolId string `json:"ResourcePoolId,omitempty"`
	// The metering port ACLs that describe what network traffic will be measured for this connection.
	MeteringAcls []MeteringPortAcl `json:"MeteringAcls,omitempty"`
	// Legacy VMMS settings as below
	FriendlyName         string `json:"FriendlyName,omitempty"`
	UseDynamicMacAddress bool   `json:"UseDynamicMacAddress,omitempty"`
	IsAttached           bool   `json:"IsAttached,omitempty"`
	// Network adapter configuration flags TODO: Only used in VMMS, might remove in HCS
	ClusterMonitored bool `json:"ClusterMonitored,omitempty"`
}
