// Autogenerated code; DO NOT EDIT.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Contact: containerplat-dev@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

// EnlightenmentModifications : Enum for enlightenment modifications
type EnlightenmentModifications string

// List of EnlightenmentModifications
const (
	EnlightenmentModifications_UNREPORTED     EnlightenmentModifications = "Unreported"
	EnlightenmentModifications_FAVOR_AUTO_EOI EnlightenmentModifications = "FavorAutoEoi"
	EnlightenmentModifications_RSVD_Z1        EnlightenmentModifications = "RsvdZ1"
)
