// Autogenerated code; DO NOT EDIT.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Contact: containerplat-dev@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

type FilesystemIsolationMode string

// List of FilesystemIsolationMode
const (
	FilesystemIsolationMode_HARD FilesystemIsolationMode = "hard"
	FilesystemIsolationMode_SOFT FilesystemIsolationMode = "soft"
)
