// Autogenerated code; DO NOT EDIT.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Contact: containerplat-dev@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

type GpuAssignmentMode string

// List of GpuAssignmentMode
const (
	GpuAssignmentMode_DISABLED GpuAssignmentMode = "Disabled"
	GpuAssignmentMode_DEFAULT_ GpuAssignmentMode = "Default"
	GpuAssignmentMode_LIST     GpuAssignmentMode = "List"
	GpuAssignmentMode_MIRROR   GpuAssignmentMode = "Mirror"
)
