// Autogenerated code; DO NOT EDIT.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Contact: containerplat-dev@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

type GuestIsolationType string

// List of GuestIsolationType
const (
	GuestIsolationType_DISABLED                       GuestIsolationType = "Disabled"
	GuestIsolationType_GUEST_STATE_ONLY               GuestIsolationType = "GuestStateOnly"
	GuestIsolationType_VIRTUALIZATION_BASED_SECURITY  GuestIsolationType = "VirtualizationBasedSecurity"
	GuestIsolationType_SECURE_NESTED_PAGING           GuestIsolationType = "SecureNestedPaging"
	GuestIsolationType_SECURE_NESTED_PAGING_EMULATION GuestIsolationType = "SecureNestedPagingEmulation"
)
