// Autogenerated code; DO NOT EDIT.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Contact: containerplat-dev@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

type GuestState struct {
	// The path to an existing file uses for persistent guest state storage. An empty string indicates the system should initialize new transient, in-memory guest state.
	GuestStateFilePath string `json:"GuestStateFilePath,omitempty"`
	// The path to an existing file for persistent runtime state storage. An empty string indicates the system should initialize new transient, in-memory runtime state.
	RuntimeStateFilePath string `json:"RuntimeStateFilePath,omitempty"`
	// If true, the guest state and runtime state files will be used as templates to populate transient, in-memory state instead of using the files as persistent backing store.
	ForceTransientState bool                `json:"ForceTransientState,omitempty"`
	GuestStateFileType  *GuestStateFileType `json:"GuestStateFileType,omitempty"`
	// The private flag to indicate if VMGS file is managed by platform or not
	FileIsPlatformManaged bool `json:"FileIsPlatformManaged,omitempty"`
}
