// Autogenerated code; DO NOT EDIT.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Contact: containerplat-dev@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

type GuestStateFileType string

// List of GuestStateFileType
const (
	GuestStateFileType_BLOCK_STORAGE GuestStateFileType = "BlockStorage"
	GuestStateFileType_FILE_MODE     GuestStateFileType = "FileMode"
)
