// Autogenerated code; DO NOT EDIT.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Contact: containerplat-dev@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

type GuestMemoryAccessTrackingHeader struct {
	Version                   uint32 `json:"Version,omitempty"`
	HeaderSizeInBytes         uint32 `json:"HeaderSizeInBytes,omitempty"`
	BitmapBufferOffsetInBytes uint32 `json:"BitmapBufferOffsetInBytes,omitempty"`
	Reserved0                 uint32 `json:"Reserved0,omitempty"`
	BitmapBufferSizeInBytes   uint64 `json:"BitmapBufferSizeInBytes,omitempty"`
}
