// Autogenerated code; DO NOT EDIT.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Contact: containerplat-dev@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

// Memory usage as viewed from the guest OS.
type GuestMemoryInfo struct {
	TotalPhysicalBytes   uint64 `json:"TotalPhysicalBytes,omitempty"`
	TotalUsage           uint64 `json:"TotalUsage,omitempty"`
	CommittedBytes       uint64 `json:"CommittedBytes,omitempty"`
	SharedCommittedBytes uint64 `json:"SharedCommittedBytes,omitempty"`
	CommitLimitBytes     uint64 `json:"CommitLimitBytes,omitempty"`
	PeakCommitmentBytes  uint64 `json:"PeakCommitmentBytes,omitempty"`
}
