// Autogenerated code; DO NOT EDIT.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Contact: containerplat-dev@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

// Information about the memory topology of a VM
type GuestPhysicalAddressRange struct {
	PageIndex uint64 `json:"PageIndex,omitempty"`
	PageCount uint64 `json:"PageCount,omitempty"`
}
