// Autogenerated code; DO NOT EDIT.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Contact: containerplat-dev@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

type GuestMemoryAccessTrackingBuffer struct {
	Header       *GuestMemoryAccessTrackingHeader `json:"Header,omitempty"`
	PageIndex    uint64                           `json:"PageIndex,omitempty"`
	PageCount    uint64                           `json:"PageCount,omitempty"`
	TrackingType uint8                            `json:"TrackingType,omitempty"`
	Reserved0    []int64                          `json:"Reserved0,omitempty"`
	Status       uint32                           `json:"Status,omitempty"`
	Generation   uint64                           `json:"Generation,omitempty"`
	BitmapBuffer []int64                          `json:"BitmapBuffer,omitempty"`
}
