// Autogenerated code; DO NOT EDIT.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Contact: containerplat-dev@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

type HostMemoryQueryType string

// List of HostMemoryQueryType
const (
	HostMemoryQueryType_DYNAMIC_MEMORY        HostMemoryQueryType = "DynamicMemory"
	HostMemoryQueryType_MEMORY_RESERVE_TARGET HostMemoryQueryType = "MemoryReserveTarget"
)
