// Autogenerated code; DO NOT EDIT.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Contact: containerplat-dev@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

// Structure used to request a service processor modification
type HostProcessorModificationRequest struct {
	Operation        *ModifyServiceOperation `json:"Operation,omitempty"`
	OperationDetails interface{}             `json:"OperationDetails,omitempty"`
}
