// Autogenerated code; DO NOT EDIT.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Contact: containerplat-dev@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

type IdledProcessorResponse struct {
	RequestedIdle uint32 `json:"RequestedIdle,omitempty"`
	IdleStatus    uint32 `json:"IdleStatus,omitempty"`
	CurrentIdle   uint32 `json:"CurrentIdle,omitempty"`
}
