// Autogenerated code; DO NOT EDIT.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Contact: containerplat-dev@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

type InterfaceClass struct {
	Type_      *InterfaceClassType `json:"type,omitempty"`
	Identifier string              `json:"identifier,omitempty"`
	Recurse    bool                `json:"recurse,omitempty"`
}
