// Autogenerated code; DO NOT EDIT.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Contact: containerplat-dev@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

// InterfaceClassType : Enum used to specify how the interface class should be treated when applying a device extension/creating container symlinks. This enum is ordering-sensitive; if two interface classes with the same identifier are merged, the type of the resulting interface class is given by the larger enum value (e.g., DeviceInstance + ClassGuid = ClassGuid).
type InterfaceClassType string

// List of InterfaceClassType
const (
	InterfaceClassType_INHERIT         InterfaceClassType = "Inherit"
	InterfaceClassType_DEVICE_INSTANCE InterfaceClassType = "DeviceInstance"
	InterfaceClassType_CLASS_GUID      InterfaceClassType = "ClassGuid"
)
