// Autogenerated code; DO NOT EDIT.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Contact: containerplat-dev@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

type IsolationSettings struct {
	IsolationType *GuestIsolationType `json:"IsolationType,omitempty"`
	// Configuration to debug HCL layer for HCS VM TODO: Task 31102306: Miss the way to prevent the exposure of private debug configuration in HCS TODO: Think about the secret configurations which are private in VMMS VM (only edit by hvsedit)
	DebugHost string `json:"DebugHost,omitempty"`
	DebugPort int64  `json:"DebugPort,omitempty"`
	// Optional data passed by host on isolated virtual machine start
	LaunchData string `json:"LaunchData,omitempty"`
	// IGVM file path, private in HCS
	IgvmFilePath string `json:"IgvmFilePath,omitempty"`
	// HCL enable flag, private in HCS TODO: Remove here if it got removed from VMMS, to load the info from IGVM file in VMWP
	HclEnabled bool `json:"HclEnabled,omitempty"`
}
