// Autogenerated code; DO NOT EDIT.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Contact: containerplat-dev@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

// Query information to request from the key-value exchange integration component
type KvpQuery struct {
	Source *KvpSource `json:"Source,omitempty"`
	// Keys in the key-value pair to be used for the query depending on the operation
	Keys []string `json:"Keys,omitempty"`
}
