// Autogenerated code; DO NOT EDIT.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Contact: containerplat-dev@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

// KvpSource : The source sets the location of the key-value pairs stored depending on the type of the key-value pairs
type KvpSource string

// List of KvpSource
const (
	KvpSource_KVP_SET_BY_HOST  KvpSource = "KvpSetByHost"
	KvpSource_KVP_SET_BY_GUEST KvpSource = "KvpSetByGuest"
	KvpSource_GUEST_OS_INFO    KvpSource = "GuestOSInfo"
)
