// Autogenerated code; DO NOT EDIT.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Contact: containerplat-dev@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

type LinuxMappedDirectory struct {
	MountPath string `json:"MountPath,omitempty"`
	Port      uint32 `json:"Port,omitempty"`
	ShareName string `json:"ShareName,omitempty"`
	ReadOnly  bool   `json:"ReadOnly,omitempty"`
}
