// Autogenerated code; DO NOT EDIT.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Contact: containerplat-dev@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

type LinuxNamespace struct {
	// pid, network, mount, ipc, uts, user, cgroup
	Type_ string `json:"type,omitempty"`
	Path  string `json:"path,omitempty"`
}
