// Autogenerated code; DO NOT EDIT.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Contact: containerplat-dev@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

type Linux struct {
	UidMappings       []LinuxIdMapping  `json:"uidMappings,omitempty"`
	GidMappings       []LinuxIdMapping  `json:"gidMappings,omitempty"`
	Sysctl            map[string]string `json:"sysctl,omitempty"`
	Resources         *LinuxResources   `json:"resources,omitempty"`
	CgroupsPath       string            `json:"cgroupsPath,omitempty"`
	Namespaces        []LinuxNamespace  `json:"namespaces,omitempty"`
	Devices           []LinuxDevice     `json:"devices,omitempty"`
	Seccomp           *LinuxSeccomp     `json:"seccomp,omitempty"`
	RootfsPropagation string            `json:"rootfsPropagation,omitempty"`
	MaskedPaths       []string          `json:"maskedPaths,omitempty"`
	ReadonlyPaths     []string          `json:"readonlyPaths,omitempty"`
	MountLabel        string            `json:"mountLabel,omitempty"`
	IntelRdt          *LinuxIntelRdt    `json:"intelRdt,omitempty"`
}
