// Autogenerated code; DO NOT EDIT.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Contact: containerplat-dev@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

type LinuxCpu struct {
	Shares          uint64 `json:"shares,omitempty"`
	Quota           int64  `json:"quota,omitempty"`
	Period          uint64 `json:"period,omitempty"`
	RealtimeRuntime int64  `json:"realtimeRuntime,omitempty"`
	RealtimePeriod  uint64 `json:"realtimePeriod,omitempty"`
	Cpus            string `json:"cpus,omitempty"`
	Mems            string `json:"mems,omitempty"`
}
