// Autogenerated code; DO NOT EDIT.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Contact: containerplat-dev@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

type LinuxMemory struct {
	Limit            int64  `json:"limit,omitempty"`
	Reservation      int64  `json:"reservation,omitempty"`
	Swap             int64  `json:"swap,omitempty"`
	Kernel           int64  `json:"kernel,omitempty"`
	KernelTCP        int64  `json:"kernelTCP,omitempty"`
	Swappiness       uint64 `json:"swappiness,omitempty"`
	DisableOOMKiller bool   `json:"disableOOMKiller,omitempty"`
}
