// Autogenerated code; DO NOT EDIT.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Contact: containerplat-dev@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

type LinuxThrottleDevice struct {
	Major int64  `json:"major,omitempty"`
	Minor int64  `json:"minor,omitempty"`
	Rate  uint64 `json:"rate,omitempty"`
}
