// Autogenerated code; DO NOT EDIT.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Contact: containerplat-dev@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

type LinuxProcessParameters struct {
	CreateStdInPipe  bool     `json:"CreateStdInPipe,omitempty"`
	CreateStdOutPipe bool     `json:"CreateStdOutPipe,omitempty"`
	CreateStdErrPipe bool     `json:"CreateStdErrPipe,omitempty"`
	OciProcess       *Process `json:"OciProcess,omitempty"`
}
