// Autogenerated code; DO NOT EDIT.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Contact: containerplat-dev@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

type LinuxModifyResourceType string

// List of Linux_ModifyResourceType
const (
	LinuxModifyResourceType_MAPPED_DIRECTORY    LinuxModifyResourceType = "MappedDirectory"
	LinuxModifyResourceType_MAPPED_VIRTUAL_DISK LinuxModifyResourceType = "MappedVirtualDisk"
	LinuxModifyResourceType_COMBINED_LAYERS     LinuxModifyResourceType = "CombinedLayers"
	LinuxModifyResourceType_VP_MEM_DEVICE       LinuxModifyResourceType = "VPMemDevice"
)
