// Autogenerated code; DO NOT EDIT.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Contact: containerplat-dev@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

type LinuxIdMapping struct {
	ContainerID uint32 `json:"containerID,omitempty"`
	HostID      uint32 `json:"hostID,omitempty"`
	Size        uint32 `json:"size,omitempty"`
}
