// Autogenerated code; DO NOT EDIT.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Contact: containerplat-dev@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

type LinuxSeccompArg struct {
	Index    uint64 `json:"index,omitempty"`
	Value    uint64 `json:"value,omitempty"`
	ValueTwo uint64 `json:"valueTwo,omitempty"`
	Op       string `json:"op,omitempty"`
}
