// Autogenerated code; DO NOT EDIT.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Contact: containerplat-dev@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

type LinuxDeviceCgroup struct {
	Allow  bool   `json:"allow,omitempty"`
	Type_  string `json:"type,omitempty"`
	Major  int64  `json:"major,omitempty"`
	Minor  int64  `json:"minor,omitempty"`
	Access string `json:"access,omitempty"`
}
