// Autogenerated code; DO NOT EDIT.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Contact: containerplat-dev@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

type LinuxDevice struct {
	Path     string `json:"path,omitempty"`
	Type_    string `json:"type,omitempty"`
	Major    int64  `json:"major,omitempty"`
	Minor    int64  `json:"minor,omitempty"`
	FileMode uint32 `json:"fileMode,omitempty"`
	Uid      uint32 `json:"uid,omitempty"`
	Gid      uint32 `json:"gid,omitempty"`
}
