// Autogenerated code; DO NOT EDIT.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Contact: containerplat-dev@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

// Configuration for a process dump using MiniDumpWriteDump
type LiveDump struct {
	// Path to create the dump file. The file must not exist.
	DumpFileName string `json:"DumpFileName,omitempty"`
	// Live dump selective control flags.
	SelectiveControlFlags uint64 `json:"SelectiveControlFlags,omitempty"`
	// Includes user space pages. Host kernel debugging must be enabled.
	IncludeUserPages bool `json:"IncludeUserPages,omitempty"`
	// Include Hypervisor pages.
	IncludeHypervisorPages bool `json:"IncludeHypervisorPages,omitempty"`
	// Includes additional hypervisor pages not normally captured. Implies IncludeHypervisorPages.
	IncludeHypervisorFullPages bool `json:"IncludeHypervisorFullPages,omitempty"`
	// Aborts the live dump if memory pressure occurs.
	AbortOnLowMemory bool `json:"AbortOnLowMemory,omitempty"`
}
