// Autogenerated code; DO NOT EDIT.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Contact: containerplat-dev@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

type MappedPipePathType string

// List of MappedPipePathType
const (
	MappedPipePathType_ABSOLUTE_PATH         MappedPipePathType = "AbsolutePath"
	MappedPipePathType_VIRTUAL_SMB_PIPE_NAME MappedPipePathType = "VirtualSmbPipeName"
)
