// Autogenerated code; DO NOT EDIT.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Contact: containerplat-dev@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

// Structure to return processor L3 cache memory bandwidth allocation settings for a Service property query.
type MemoryBwAllocationSystemInfo struct {
	MbaSupported        bool    `json:"MbaSupported,omitempty"`
	MbaLinear           bool    `json:"MbaLinear,omitempty"`
	MaxMbaCos           uint32  `json:"MaxMbaCos,omitempty"`
	MaxMbaThrottleValue uint32  `json:"MaxMbaThrottleValue,omitempty"`
	MbaCosSlots         []int64 `json:"MbaCosSlots,omitempty"`
}
