// Autogenerated code; DO NOT EDIT.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Contact: containerplat-dev@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

type MemoryIoSpaceConversionOperation struct {
	NumaNodeIndex       uint8  `json:"NumaNodeIndex,omitempty"`
	MemoryPartitionName string `json:"MemoryPartitionName,omitempty"`
	Promote             bool   `json:"Promote,omitempty"`
	AnyNodeOkay         bool   `json:"AnyNodeOkay,omitempty"`
	BadPagesOnly        bool   `json:"BadPagesOnly,omitempty"`
}
