// Autogenerated code; DO NOT EDIT.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Contact: containerplat-dev@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

type MemoryInformationForHost struct {
	// Number of physical NUMA nodes on the host.
	NumaNodeCount         uint8       `json:"NumaNodeCount,omitempty"`
	HostMemoryInformation *HostMemory `json:"HostMemoryInformation,omitempty"`
	// Physical NUMA node specific information (see NumaNodeMemory).
	NumaNodes []NumaNodeMemory `json:"NumaNodes,omitempty"`
	// Memory balancer specific information (see MemoryBalancerInfo).
	Balancers []MemoryBalancerInfo `json:"Balancers,omitempty"`
}
