// Autogenerated code; DO NOT EDIT.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Contact: containerplat-dev@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

type MemoryBalancerInfo struct {
	// Currently available physical memory with this balancer instance.
	AvailableMemoryInPages uint64 `json:"AvailableMemoryInPages,omitempty"`
	// Host available memory with this balancer instance after accounting for pages freed due to applying pressure.
	AvailableMemoryForStartingVmsInPages uint64 `json:"AvailableMemoryForStartingVmsInPages,omitempty"`
}
