// Autogenerated code; DO NOT EDIT.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Contact: containerplat-dev@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

// The response of memory information for virtual machine when query memory property of compute system
type MemoryInformationForVm struct {
	VirtualNodeCount     uint8             `json:"VirtualNodeCount,omitempty"`
	VirtualMachineMemory *VmMemory         `json:"VirtualMachineMemory,omitempty"`
	VirtualNodes         []VirtualNodeInfo `json:"VirtualNodes,omitempty"`
}
