// Autogenerated code; DO NOT EDIT.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Contact: containerplat-dev@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

type MemoryReserveResizeOperation struct {
	NumaNodeIndex       uint8                  `json:"NumaNodeIndex,omitempty"`
	MemoryPartitionName string                 `json:"MemoryPartitionName,omitempty"`
	PageCount           uint64                 `json:"PageCount,omitempty"`
	PageSize            *MemoryReservePageSize `json:"PageSize,omitempty"`
	AnyNodeOkay         bool                   `json:"AnyNodeOkay,omitempty"`
	// Only returns pages with addresses higher than 4 GB.
	Above4Gb     bool `json:"Above4Gb,omitempty"`
	DemoteOnMove bool `json:"DemoteOnMove,omitempty"`
}
