// Autogenerated code; DO NOT EDIT.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Contact: containerplat-dev@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

type MemoryReservePageSize string

// List of MemoryReservePageSize
const (
	MemoryReservePageSize_NO_PREFERENCE        MemoryReservePageSize = "NoPreference"
	MemoryReservePageSize_HUGE_PAGES_ONLY      MemoryReservePageSize = "HugePagesOnly"
	MemoryReservePageSize_FAST_PAGES_ONLY      MemoryReservePageSize = "FastPagesOnly"
	MemoryReservePageSize_FAST_HUGE_PAGES_ONLY MemoryReservePageSize = "FastHugePagesOnly"
	MemoryReservePageSize_ANY_PAGES_OKAY       MemoryReservePageSize = "AnyPagesOkay"
)
