// Autogenerated code; DO NOT EDIT.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Contact: containerplat-dev@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

// A port ACL (access control list) that expresses a rule for measuring network traffic based on IP address range and direction.
type MeteringPortAcl struct {
	Disposition *FeatureSettingDisposition `json:"Disposition,omitempty"`
	// Whether to measure inbound network traffic, as opposed to outbound.
	IsInbound bool `json:"IsInbound,omitempty"`
	// The range of IP addresses over which to measure the traffic.
	IPAddressRange string `json:"IPAddressRange,omitempty"`
	// The unique identifier for this port ACL instance.
	InstanceId string `json:"InstanceId,omitempty"`
}
