// Autogenerated code; DO NOT EDIT.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Contact: containerplat-dev@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

// Structure used for service level modification request. Right now, we support modification of a single property type in a call.
type ModificationRequest struct {
	PropertyType *ModifyPropertyType `json:"PropertyType,omitempty"`
	// Settings to the modification request
	Settings interface{} `json:"Settings,omitempty"`
}
