// Autogenerated code; DO NOT EDIT.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Contact: containerplat-dev@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

type NetworkPropertyQuery struct {
	// The list of properties to be queried for
	NetworkProperties []PropertyQueryNetworkProperty `json:"NetworkProperties,omitempty"`
	// The map of the name of the network adapters and the type of the network adapter
	NetworkAdapterNames map[string]NetworkAdapterType `json:"NetworkAdapterNames,omitempty"`
}
