// Autogenerated code; DO NOT EDIT.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Contact: containerplat-dev@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

type NetworkAdapter struct {
	EndpointId string `json:"EndpointId,omitempty"`
	MacAddress string `json:"MacAddress,omitempty"`
	MediaType  uint32 `json:"MediaType,omitempty"`
	InstanceId string `json:"InstanceId,omitempty"`
	// Disable interrupt batching (MNF) for network to decrease latency and increase throughput, at per-interrupt processing cost.
	DisableInterruptBatching bool                `json:"DisableInterruptBatching,omitempty"`
	IovSettings              *IovSettings        `json:"IovSettings,omitempty"`
	ConnectionState          *StateOverride      `json:"ConnectionState,omitempty"`
	NetworkAdapterType       *NetworkAdapterType `json:"NetworkAdapterType,omitempty"`
	// Identification of the connected switch
	SwitchId string `json:"SwitchId,omitempty"`
	// Identification of the connected port that is part of the switch
	PortId string `json:"PortId,omitempty"`
	// Name of the switch
	SwitchName string `json:"SwitchName,omitempty"`
	// Whether the switch port used by this network adapter is configured to persist across reboots, used to support legacy scenarios. Persistent ports are heavier-weight than transient ports, which are cleaned up on host exit.
	UsePersistentPort bool `json:"UsePersistentPort,omitempty"`
	// The resource pool ID associated with this network adapter, used to report network metrics aggregated by that resource pool.
	ResourcePoolId string `json:"ResourcePoolId,omitempty"`
	// The metering port ACLs that describe what network traffic will be measured for this connection.
	MeteringAcls []MeteringPortAcl `json:"MeteringAcls,omitempty"`
	// VPCI instance Guid
	VpciInstanceGuid string `json:"VpciInstanceGuid,omitempty"`
	// Legacy VMMS settings as below
	FriendlyName         string `json:"FriendlyName,omitempty"`
	UseDynamicMacAddress bool   `json:"UseDynamicMacAddress,omitempty"`
	// TODO: Only used in VMMS, might remove in HCS
	IsConnected bool `json:"IsConnected,omitempty"`
	// Network adapter configuration flags TODO: Only used in VMMS, might remove in HCS
	ClusterMonitored         bool `json:"ClusterMonitored,omitempty"`
	DeviceNamingEnabled      bool `json:"DeviceNamingEnabled,omitempty"`
	AllowPacketDirect        bool `json:"AllowPacketDirect,omitempty"`
	NumaAwarePlacement       bool `json:"NumaAwarePlacement,omitempty"`
	AllowDirectTranslatedP2P bool `json:"AllowDirectTranslatedP2P,omitempty"`
}
