// Autogenerated code; DO NOT EDIT.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Contact: containerplat-dev@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

// The modify setting request when ResourceType is Network in GuestModifySettingRequest
type NetworkModifySettingRequest struct {
	RequestType *NetworkModifyRequestType `json:"RequestType,omitempty"`
	AdapterId   string                    `json:"AdapterId,omitempty"`
	Settings    interface{}               `json:"Settings,omitempty"`
}
