// Autogenerated code; DO NOT EDIT.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Contact: containerplat-dev@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

// NetworkAdapterType : Type of the network adapter
type NetworkAdapterType string

// List of NetworkAdapterType
const (
	NetworkAdapterType_SYNTHETIC NetworkAdapterType = "Synthetic"
	NetworkAdapterType_EMULATED  NetworkAdapterType = "Emulated"
)
