// Autogenerated code; DO NOT EDIT.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Contact: containerplat-dev@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

// NetworkModifyRequestType : The modify request type when ResourceType is Network in GuestModifySettingRequest
type NetworkModifyRequestType string

// List of NetworkModifyRequestType
const (
	NetworkModifyRequestType_PRE_ADD NetworkModifyRequestType = "PreAdd"
	NetworkModifyRequestType_ADD     NetworkModifyRequestType = "Add"
	NetworkModifyRequestType_REMOVE  NetworkModifyRequestType = "Remove"
)
