// Autogenerated code; DO NOT EDIT.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Contact: containerplat-dev@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

// NotificationType : Exit type of a compute system.
type NotificationType string

// List of NotificationType
const (
	NotificationType_NONE            NotificationType = "None"
	NotificationType_GRACEFUL_EXIT   NotificationType = "GracefulExit"
	NotificationType_FORCED_EXIT     NotificationType = "ForcedExit"
	NotificationType_UNEXPECTED_EXIT NotificationType = "UnexpectedExit"
	NotificationType_UNKNOWN         NotificationType = "Unknown"
)
