// Autogenerated code; DO NOT EDIT.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Contact: containerplat-dev@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

type ObjectSymlink struct {
	Name        string              `json:"name,omitempty"`
	Path        string              `json:"path,omitempty"`
	Scope       *ObjectSymlinkScope `json:"scope,omitempty"`
	Pathtoclone string              `json:"pathtoclone,omitempty"`
	AccessMask  uint32              `json:"access_mask,omitempty"`
}
