// Autogenerated code; DO NOT EDIT.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Contact: containerplat-dev@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

type OciSpec struct {
	OciVersion  string            `json:"ociVersion,omitempty"`
	Process     *Process          `json:"process,omitempty"`
	Root        *Root             `json:"root,omitempty"`
	Hostname    string            `json:"hostname,omitempty"`
	Mounts      []Mount           `json:"mounts,omitempty"`
	Hooks       *Hooks            `json:"hooks,omitempty"`
	Annotations map[string]string `json:"annotations,omitempty"`
	Linux       *Linux            `json:"linux,omitempty"`
}
