// Autogenerated code; DO NOT EDIT.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Contact: containerplat-dev@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

// Information about the progress of an operation
type OperationProgress struct {
	// Current progress of a task, which has a range 0-100
	CurrentProgress uint8 `json:"CurrentProgress,omitempty"`
}
