// Autogenerated code; DO NOT EDIT.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Contact: containerplat-dev@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

// OperationType : TODO: Replace usage of ActiveOperation with this?
type OperationType string

// List of OperationType
const (
	OperationType_NONE                     OperationType = "None"
	OperationType_CONSTRUCT                OperationType = "Construct"
	OperationType_START                    OperationType = "Start"
	OperationType_PAUSE                    OperationType = "Pause"
	OperationType_RESUME                   OperationType = "Resume"
	OperationType_SHUTDOWN                 OperationType = "Shutdown"
	OperationType_TERMINATE                OperationType = "Terminate"
	OperationType_SAVE                     OperationType = "Save"
	OperationType_GET_PROPERTIES           OperationType = "GetProperties"
	OperationType_MODIFY                   OperationType = "Modify"
	OperationType_CRASH                    OperationType = "Crash"
	OperationType_GUEST_CRASH              OperationType = "GuestCrash"
	OperationType_LIFECYCLE_NOTIFY         OperationType = "LifecycleNotify"
	OperationType_EXECUTE_PROCESS          OperationType = "ExecuteProcess"
	OperationType_GET_PROCESS_INFO         OperationType = "GetProcessInfo"
	OperationType_WAIT_FOR_PROCESS         OperationType = "WaitForProcess"
	OperationType_SIGNAL_PROCESS           OperationType = "SignalProcess"
	OperationType_MODIFY_PROCESS           OperationType = "ModifyProcess"
	OperationType_PREPARE_FOR_HOSTING      OperationType = "PrepareForHosting"
	OperationType_REGISTER_HOSTED_SYSTEM   OperationType = "RegisterHostedSystem"
	OperationType_UNREGISTER_HOSTED_SYSTEM OperationType = "UnregisterHostedSystem"
	OperationType_PREPARE_FOR_CLONE        OperationType = "PrepareForClone"
	OperationType_GET_CLONE_TEMPLATE       OperationType = "GetCloneTemplate"
	OperationType_CANCEL_OPERATION         OperationType = "CancelOperation"
)
