// Autogenerated code; DO NOT EDIT.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Contact: containerplat-dev@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

// PauseReason : Pause reason that is indicated to components running in the Virtual Machine.
type PauseReason string

// List of PauseReason
const (
	PauseReason_NONE     PauseReason = "None"
	PauseReason_SAVE     PauseReason = "Save"
	PauseReason_TEMPLATE PauseReason = "Template"
)
