// Autogenerated code; DO NOT EDIT.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Contact: containerplat-dev@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

type PauseSuspensionLevel string

// List of PauseSuspensionLevel
const (
	PauseSuspensionLevel_SUSPEND       PauseSuspensionLevel = "Suspend"
	PauseSuspensionLevel_MEMORY_LOW    PauseSuspensionLevel = "MemoryLow"
	PauseSuspensionLevel_MEMORY_MEDIUM PauseSuspensionLevel = "MemoryMedium"
	PauseSuspensionLevel_MEMORY_HIGH   PauseSuspensionLevel = "MemoryHigh"
)
