// Autogenerated code; DO NOT EDIT.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Contact: containerplat-dev@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

type Plan9Share struct {
	Name string `json:"Name,omitempty"`
	// The name by which the guest operation system can access this share, via the aname parameter in the Plan9 protocol.
	AccessName   string   `json:"AccessName,omitempty"`
	Path         string   `json:"Path,omitempty"`
	Port         uint32   `json:"Port,omitempty"`
	Flags        int64    `json:"Flags,omitempty"`
	AllowedFiles []string `json:"AllowedFiles,omitempty"`
}
