// Autogenerated code; DO NOT EDIT.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Contact: containerplat-dev@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

// Passed to HcsRpc_ModifyProcess
type ProcessModifyRequest struct {
	Operation   *ModifyOperation `json:"Operation,omitempty"`
	ConsoleSize *ConsoleSize     `json:"ConsoleSize,omitempty"`
	CloseHandle *CloseHandle     `json:"CloseHandle,omitempty"`
}
