// Autogenerated code; DO NOT EDIT.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Contact: containerplat-dev@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

type Process struct {
	Terminal        bool               `json:"terminal,omitempty"`
	ConsoleSize     *Box               `json:"consoleSize,omitempty"`
	User            *User              `json:"user,omitempty"`
	Args            []string           `json:"args,omitempty"`
	Env             []string           `json:"env,omitempty"`
	Cwd             string             `json:"cwd,omitempty"`
	Capabilities    *LinuxCapabilities `json:"capabilities,omitempty"`
	NoNewPrivileges bool               `json:"noNewPrivileges,omitempty"`
	ApparmorProfile string             `json:"apparmorProfile,omitempty"`
	OomScoreAdj     int64              `json:"oomScoreAdj,omitempty"`
	SelinuxLabel    string             `json:"selinuxLabel,omitempty"`
}
