// Autogenerated code; DO NOT EDIT.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Contact: containerplat-dev@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

type ProcessSignal string

// List of ProcessSignal
const (
	ProcessSignal_CTRL_C        ProcessSignal = "CtrlC"
	ProcessSignal_CTRL_BREAK    ProcessSignal = "CtrlBreak"
	ProcessSignal_CTRL_CLOSE    ProcessSignal = "CtrlClose"
	ProcessSignal_CTRL_LOG_OFF  ProcessSignal = "CtrlLogOff"
	ProcessSignal_CTRL_SHUTDOWN ProcessSignal = "CtrlShutdown"
)
