// Autogenerated code; DO NOT EDIT.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Contact: containerplat-dev@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

// ProcessDumpType : Indicates the type of process dump to be captured.
type ProcessDumpType string

// List of ProcessDumpType
const (
	ProcessDumpType_NONE   ProcessDumpType = "None"
	ProcessDumpType_HEAP   ProcessDumpType = "Heap"
	ProcessDumpType_MINI   ProcessDumpType = "Mini"
	ProcessDumpType_CUSTOM ProcessDumpType = "Custom"
)
