// Autogenerated code; DO NOT EDIT.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Contact: containerplat-dev@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

// Structure used to return processor topology for a Service property query
type ProcessorTopology struct {
	LogicalProcessorCount uint32             `json:"LogicalProcessorCount,omitempty"`
	LogicalProcessors     []LogicalProcessor `json:"LogicalProcessors,omitempty"`
}
