// Autogenerated code; DO NOT EDIT.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Contact: containerplat-dev@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

// VM specific processor feature requirements
type ProcessorFeatureSet struct {
	// Processor features
	ProcessorFeatures []ProcessorFeature `json:"ProcessorFeatures,omitempty"`
	// Xsave processor features
	XsaveProcessorFeatures  []XsaveProcessorFeature  `json:"XsaveProcessorFeatures,omitempty"`
	ProcessorFeatureSetMode *ProcessorFeatureSetMode `json:"ProcessorFeatureSetMode,omitempty"`
}
