// Autogenerated code; DO NOT EDIT.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Contact: containerplat-dev@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

type Properties struct {
	Id                          string                   `json:"Id,omitempty"`
	SystemType                  *SystemType              `json:"SystemType,omitempty"`
	RuntimeOsType               *OsType                  `json:"RuntimeOsType,omitempty"`
	Name                        string                   `json:"Name,omitempty"`
	Owner                       string                   `json:"Owner,omitempty"`
	ObRoot                      string                   `json:"ObRoot,omitempty"`
	IsDummy                     bool                     `json:"IsDummy,omitempty"`
	RuntimeId                   string                   `json:"RuntimeId,omitempty"`
	RuntimeImagePath            string                   `json:"RuntimeImagePath,omitempty"`
	IsRuntimeTemplate           bool                     `json:"IsRuntimeTemplate,omitempty"`
	RuntimeTemplateId           string                   `json:"RuntimeTemplateId,omitempty"`
	State                       *State                   `json:"State,omitempty"`
	Stopped                     bool                     `json:"Stopped,omitempty"`
	ExitType                    *NotificationType        `json:"ExitType,omitempty"`
	Memory                      *MemoryInformationForVm  `json:"Memory,omitempty"`
	GuestMemoryInfo             *GuestMemoryInfo         `json:"GuestMemoryInfo,omitempty"`
	CpuGroupId                  string                   `json:"CpuGroupId,omitempty"`
	Statistics                  *Statistics              `json:"Statistics,omitempty"`
	ProcessList                 []ProcessDetails         `json:"ProcessList,omitempty"`
	TerminateOnLastHandleClosed bool                     `json:"TerminateOnLastHandleClosed,omitempty"`
	SystemGUID                  string                   `json:"SystemGUID,omitempty"`
	HostingSystemId             string                   `json:"HostingSystemId,omitempty"`
	SharedMemoryRegionInfo      []SharedMemoryRegionInfo `json:"SharedMemoryRegionInfo,omitempty"`
	GuestConnectionInfo         *GuestConnectionInfo     `json:"GuestConnectionInfo,omitempty"`
	Silo                        *SiloProperties          `json:"Silo,omitempty"`
	CosIndex                    uint32                   `json:"CosIndex,omitempty"`
	Rmid                        uint32                   `json:"Rmid,omitempty"`
	CacheStats                  *CacheQueryStatsResponse `json:"CacheStats,omitempty"`
	IdledProcessorInfo          *IdledProcessorResponse  `json:"IdledProcessorInfo,omitempty"`
	CpuFrequencyPowerCap        uint32                   `json:"CpuFrequencyPowerCap,omitempty"`
	// This is a new response object, introduced in version 2.5, which maps the requested property names to their associated response objects.
	PropertyResponses map[string]PropertyResponse `json:"PropertyResponses,omitempty"`
}
