// Autogenerated code; DO NOT EDIT.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Contact: containerplat-dev@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

// PxeProtocol : Used for VMMS VM only, represent PxeProtocol for bios loader device
type PxeProtocol string

// List of PxeProtocol
const (
	PxeProtocol_UNKNOWN PxeProtocol = "Unknown"
	PxeProtocol_IPV4    PxeProtocol = "IPv4"
	PxeProtocol_IPV6    PxeProtocol = "IPv6"
)
