// Autogenerated code; DO NOT EDIT.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Contact: containerplat-dev@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

type RdpConnectionOptions struct {
	AccessSids []string `json:"AccessSids,omitempty"`
	NamedPipe  string   `json:"NamedPipe,omitempty"`
	// The transport type used to connect to the guest RDP service.
	TransportType int64 `json:"TransportType,omitempty"`
}
