// Autogenerated code; DO NOT EDIT.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Contact: containerplat-dev@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

type RegistryHive string

// List of RegistryHive
const (
	RegistryHive_SYSTEM   RegistryHive = "System"
	RegistryHive_SOFTWARE RegistryHive = "Software"
	RegistryHive_SECURITY RegistryHive = "Security"
	RegistryHive_SAM      RegistryHive = "Sam"
)
