// Autogenerated code; DO NOT EDIT.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Contact: containerplat-dev@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

type RegistryMakeValue struct {
	Name            string `json:"name,omitempty"`
	DataMultistring string `json:"data_multistring,omitempty"`
	DataDword       uint32 `json:"data_dword,omitempty"`
	DataString      string `json:"data_string,omitempty"`
	DataBinary      string `json:"data_binary,omitempty"`
}
