// Autogenerated code; DO NOT EDIT.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Contact: containerplat-dev@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

type RegistryRedirectionNode struct {
	Containerpath string `json:"containerpath,omitempty"`
	Hostpath      string `json:"hostpath,omitempty"`
	Hivestack     string `json:"hivestack,omitempty"`
	AccessMask    uint32 `json:"access_mask,omitempty"`
	Trustedhive   bool   `json:"trustedhive,omitempty"`
	Exitnode      bool   `json:"exitnode,omitempty"`
}
