// Autogenerated code; DO NOT EDIT.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Contact: containerplat-dev@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

type RegistryValue struct {
	Key   *RegistryKey       `json:"Key,omitempty"`
	Name  string             `json:"Name,omitempty"`
	Type_ *RegistryValueType `json:"Type,omitempty"`
	// One and only one value type must be set.
	StringValue string `json:"StringValue,omitempty"`
	BinaryValue string `json:"BinaryValue,omitempty"`
	DWordValue  uint32 `json:"DWordValue,omitempty"`
	QWordValue  uint64 `json:"QWordValue,omitempty"`
	// Only used if RegistryValueType is CustomType The data is in BinaryValue
	CustomType uint32 `json:"CustomType,omitempty"`
}
