// Autogenerated code; DO NOT EDIT.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Contact: containerplat-dev@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

// ResolutionType : The resolution type used for VideoMonitor resolution settings
type ResolutionType string

// List of ResolutionType
const (
	ResolutionType_UNSPECIFIED ResolutionType = "Unspecified"
	ResolutionType_MAXIMUM     ResolutionType = "Maximum"
	ResolutionType_SINGLE      ResolutionType = "Single"
	ResolutionType_DEFAULT_    ResolutionType = "Default"
)
