// Autogenerated code; DO NOT EDIT.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Contact: containerplat-dev@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

type Root struct {
	Path string `json:"path,omitempty"`
	// If we make the actual field name `readonly`, it will produce invalid C#.
	Readonly bool `json:"readonly,omitempty"`
}
