// Autogenerated code; DO NOT EDIT.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Contact: containerplat-dev@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

// This class is only necessary because JSON marshaling complains when we have two fields identical except for capitalization in the same class. Remove this once we stop supporting RS4.
type Rs4NetworkModifySettingRequest struct {
	RequestType       *NetworkModifyRequestType `json:"RequestType,omitempty"`
	AdapterInstanceID string                    `json:"AdapterInstanceID,omitempty"`
	Settings          interface{}               `json:"Settings,omitempty"`
}
