// Autogenerated code; DO NOT EDIT.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Contact: containerplat-dev@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

type SaveType string

// List of SaveType
const (
	SaveType_TO_FILE     SaveType = "ToFile"
	SaveType_AS_TEMPLATE SaveType = "AsTemplate"
)
