// Autogenerated code; DO NOT EDIT.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Contact: containerplat-dev@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

type SecuritySettings struct {
	// Enablement of Trusted Platform Module on the computer system TODO: might be removed since it will be replaced by HCL isolation settings
	EnableTpm bool               `json:"EnableTpm,omitempty"`
	Isolation *IsolationSettings `json:"Isolation,omitempty"`
}
