// Autogenerated code; DO NOT EDIT.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Contact: containerplat-dev@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

// An identifier unique to each physical CPU package.
type SecureNestedPagingCpuId struct {
	// Per package CPU identifier.
	Id []int64 `json:"Id,omitempty"`
}
