// Autogenerated code; DO NOT EDIT.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Contact: containerplat-dev@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

// AMD SEV-SNP (secure nested paging) information required for attestation.
type SecureNestedPagingInfo struct {
	// List of IDs per socket.
	CpuId []SecureNestedPagingCpuId `json:"CpuId,omitempty"`
	// SNP TCB (trusted computing base) version.
	TcbVersion uint64 `json:"TcbVersion,omitempty"`
}
