// Autogenerated code; DO NOT EDIT.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Contact: containerplat-dev@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

type SerialConsole string

// List of SerialConsole
const (
	SerialConsole_DEFAULT_  SerialConsole = "Default"
	SerialConsole_DISABLED  SerialConsole = "Disabled"
	SerialConsole_COM_PORT1 SerialConsole = "ComPort1"
	SerialConsole_COM_PORT2 SerialConsole = "ComPort2"
)
