// Autogenerated code; DO NOT EDIT.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Contact: containerplat-dev@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

// Structure used to perform property query
type ServicePropertyQuery struct {
	// Specifies the property array to query
	PropertyTypes []GetPropertyType `json:"PropertyTypes,omitempty"`
	// Perform filtered property queries
	FilteredQueries []FilteredPropertyQuery `json:"FilteredQueries,omitempty"`
	PropertyQueries map[string]interface{}  `json:"PropertyQueries,omitempty"`
}
