// Autogenerated code; DO NOT EDIT.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Contact: containerplat-dev@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

// State : Compute system state which is exposed to external clients
type State string

// List of State
const (
	State_CREATED           State = "Created"
	State_RUNNING           State = "Running"
	State_PAUSED            State = "Paused"
	State_STOPPED           State = "Stopped"
	State_SAVED_AS_TEMPLATE State = "SavedAsTemplate"
	State_UNKNOWN           State = "Unknown"
)
