// Autogenerated code; DO NOT EDIT.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Contact: containerplat-dev@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

type StdHandle string

// List of StdHandle
const (
	StdHandle_STD_IN  StdHandle = "StdIn"
	StdHandle_STD_OUT StdHandle = "StdOut"
	StdHandle_STD_ERR StdHandle = "StdErr"
	StdHandle_ALL     StdHandle = "All"
)
