// Autogenerated code; DO NOT EDIT.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Contact: containerplat-dev@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

// Describes storage quality of service settings, relative to a storage volume.
type StorageQoS struct {
	// Defines the maximum allowed Input/Output operations per second in a volume.
	IopsMaximum uint64 `json:"IopsMaximum,omitempty"`
	// Defines the maximum bandwidth (bytes per second) allowed in a volume.
	BandwidthMaximum uint64 `json:"BandwidthMaximum,omitempty"`
}
