// Autogenerated code; DO NOT EDIT.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Contact: containerplat-dev@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

type SubnodeType string

// List of SubnodeType
const (
	SubnodeType_ANY     SubnodeType = "Any"
	SubnodeType_SOCKET  SubnodeType = "Socket"
	SubnodeType_CLUSTER SubnodeType = "Cluster"
	SubnodeType_L3      SubnodeType = "L3"
)
