// Autogenerated code; DO NOT EDIT.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Contact: containerplat-dev@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

type SystemTime struct {
	Year         uint16 `json:"Year,omitempty"`
	Month        uint16 `json:"Month,omitempty"`
	DayOfWeek    uint16 `json:"DayOfWeek,omitempty"`
	Day          uint16 `json:"Day,omitempty"`
	Hour         uint16 `json:"Hour,omitempty"`
	Minute       uint16 `json:"Minute,omitempty"`
	Second       uint16 `json:"Second,omitempty"`
	Milliseconds uint16 `json:"Milliseconds,omitempty"`
}
