// Autogenerated code; DO NOT EDIT.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Contact: containerplat-dev@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

type TransportType string

// List of TransportType
const (
	TransportType_VM_BUS    TransportType = "VMBus"
	TransportType_HV_SOCKET TransportType = "HvSocket"
)
