// Autogenerated code; DO NOT EDIT.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Contact: containerplat-dev@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

type UefiSystemInformation struct {
	Manufacturer string `json:"Manufacturer,omitempty"`
	ProductName  string `json:"ProductName,omitempty"`
	Version      string `json:"Version,omitempty"`
	SerialNumber string `json:"SerialNumber,omitempty"`
	UUID         string `json:"UUID,omitempty"`
	SKUNumber    string `json:"SKUNumber,omitempty"`
	Family       string `json:"Family,omitempty"`
}
