// Autogenerated code; DO NOT EDIT.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Contact: containerplat-dev@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

type Uefi struct {
	EnableDebugger          bool                         `json:"EnableDebugger,omitempty"`
	SecureBootTemplateId    string                       `json:"SecureBootTemplateId,omitempty"`
	ApplySecureBootTemplate *ApplySecureBootTemplateType `json:"ApplySecureBootTemplate,omitempty"`
	BootThis                *UefiBootEntry               `json:"BootThis,omitempty"`
	Console                 *SerialConsole               `json:"Console,omitempty"`
	StopOnBootFailure       bool                         `json:"StopOnBootFailure,omitempty"`
	// Biosflag LoadOempTable
	LoadOempTable                bool   `json:"LoadOempTable,omitempty"`
	PauseAfterBootFailure        bool   `json:"PauseAfterBootFailure,omitempty"`
	ImcData                      string `json:"ImcData,omitempty"`
	MemoryAttributes             bool   `json:"MemoryAttributes,omitempty"`
	DisableSha384Pcr             bool   `json:"DisableSha384Pcr,omitempty"`
	BootPciExpress               bool   `json:"BootPciExpress,omitempty"`
	BootPciExpressInstanceFilter string `json:"BootPciExpressInstanceFilter,omitempty"`
}
