// Autogenerated code; DO NOT EDIT.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Contact: containerplat-dev@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

type User struct {
	Uid            uint32  `json:"uid,omitempty"`
	Gid            uint32  `json:"gid,omitempty"`
	AdditionalGids []int64 `json:"additionalGids,omitempty"`
	Username       string  `json:"username,omitempty"`
}
