// Autogenerated code; DO NOT EDIT.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Contact: containerplat-dev@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

type VideoMonitor struct {
	HorizontalResolution uint16                `json:"HorizontalResolution,omitempty"`
	VerticalResolution   uint16                `json:"VerticalResolution,omitempty"`
	ConnectionOptions    *RdpConnectionOptions `json:"ConnectionOptions,omitempty"`
	ResolutionType       int64                 `json:"ResolutionType,omitempty"`
	// Only VMMS VM configuration, set to true only in generation 1 VMs only when the VGA device is present
	SecondaryDevice bool `json:"SecondaryDevice,omitempty"`
}
