// Autogenerated code; DO NOT EDIT.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Contact: containerplat-dev@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

type VirtualSmbShare struct {
	Name                           string                          `json:"Name,omitempty"`
	Path                           string                          `json:"Path,omitempty"`
	Flags                          int64                           `json:"Flags,omitempty"`
	AllowedFiles                   []string                        `json:"AllowedFiles,omitempty"`
	AllowedFsctls                  []int64                         `json:"AllowedFsctls,omitempty"`
	PrefetchFiles                  []string                        `json:"PrefetchFiles,omitempty"`
	AutoCreateAlternateDataStreams []VirtualSmbAlternateDataStream `json:"AutoCreateAlternateDataStreams,omitempty"`
	Options                        *VirtualSmbShareOptions         `json:"Options,omitempty"`
}
