// Autogenerated code; DO NOT EDIT.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Contact: containerplat-dev@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

type VirtualNodeInfo struct {
	VirtualNodeIndex      uint8  `json:"VirtualNodeIndex,omitempty"`
	PhysicalNodeNumber    uint8  `json:"PhysicalNodeNumber,omitempty"`
	VirtualProcessorCount uint32 `json:"VirtualProcessorCount,omitempty"`
	MemoryUsageInPages    uint64 `json:"MemoryUsageInPages,omitempty"`
}
