// Autogenerated code; DO NOT EDIT.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Contact: containerplat-dev@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

type VirtualPMemImageFormat string

// List of VirtualPMemImageFormat
const (
	VirtualPMemImageFormat_VHDX VirtualPMemImageFormat = "Vhdx"
	VirtualPMemImageFormat_VHD1 VirtualPMemImageFormat = "Vhd1"
)
