// Autogenerated code; DO NOT EDIT.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Contact: containerplat-dev@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

type VmLifecycleInfo struct {
	// RawReason is the integer value showing VM state change reasons, only used by HCS internal clients. Please ignore it if you don't know its meaning.
	RawReason uint32 `json:"RawReason,omitempty"`
	// RawState is the integer value showing uncommon VM states, only used by HCS internal clients. Please ignore it if you don't know its meaning.
	RawState uint32 `json:"RawState,omitempty"`
}
