// Autogenerated code; DO NOT EDIT.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Contact: containerplat-dev@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

// Windows specific crash information
type WindowsCrashReport struct {
	// Path to a Windows memory dump file. This will contain the same path as the configured in the GuestCrashReporting device. This field is not valid unless the FinalPhase is Complete.
	DumpFile string `json:"DumpFile,omitempty"`
	// Major version as reported by the guest OS.
	OsMajorVersion uint32 `json:"OsMajorVersion,omitempty"`
	// Minor version as reported by the guest OS.
	OsMinorVersion uint32 `json:"OsMinorVersion,omitempty"`
	// Build number as reported by the guest OS.
	OsBuildNumber uint32 `json:"OsBuildNumber,omitempty"`
	// Service pack major version as reported by the guest OS.
	OsServicePackMajorVersion uint32 `json:"OsServicePackMajorVersion,omitempty"`
	// Service pack minor version as reported by the guest OS.
	OsServicePackMinorVersion uint32 `json:"OsServicePackMinorVersion,omitempty"`
	// Suite mask as reported by the guest OS.
	OsSuiteMask uint32 `json:"OsSuiteMask,omitempty"`
	// Product type as reported by the guest OS.
	OsProductType uint32 `json:"OsProductType,omitempty"`
	// Status of the crash dump. S_OK indicates success, other HRESULT values on error.
	Status     int32              `json:"Status,omitempty"`
	FinalPhase *WindowsCrashPhase `json:"FinalPhase,omitempty"`
}
