// Autogenerated code; DO NOT EDIT.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Contact: containerplat-dev@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

type WindowsCrashDumpType string

// List of WindowsCrashDumpType
const (
	WindowsCrashDumpType_DISABLED      WindowsCrashDumpType = "Disabled"
	WindowsCrashDumpType_FULL          WindowsCrashDumpType = "Full"
	WindowsCrashDumpType_SUMMARY       WindowsCrashDumpType = "Summary"
	WindowsCrashDumpType_HEADER        WindowsCrashDumpType = "Header"
	WindowsCrashDumpType_TRIAGE        WindowsCrashDumpType = "Triage"
	WindowsCrashDumpType_BITMAP_FULL   WindowsCrashDumpType = "BitmapFull"
	WindowsCrashDumpType_BITMAP_KERNEL WindowsCrashDumpType = "BitmapKernel"
	WindowsCrashDumpType_AUTOMATIC     WindowsCrashDumpType = "Automatic"
)
