// Autogenerated code; DO NOT EDIT.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Contact: containerplat-dev@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

// WindowsCrashPhase : Indicated the progress of a Windows memory dump in a WindowsCrashReport.
type WindowsCrashPhase string

// List of WindowsCrashPhase
const (
	WindowsCrashPhase_INACTIVE     WindowsCrashPhase = "Inactive"
	WindowsCrashPhase_CRASH_VALUES WindowsCrashPhase = "CrashValues"
	WindowsCrashPhase_STARTING     WindowsCrashPhase = "Starting"
	WindowsCrashPhase_STARTED      WindowsCrashPhase = "Started"
	WindowsCrashPhase_WRITING      WindowsCrashPhase = "Writing"
	WindowsCrashPhase_COMPLETE     WindowsCrashPhase = "Complete"
)
