// Autogenerated code; DO NOT EDIT.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Contact: containerplat-dev@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

type WindowsCrashReporting struct {
	DumpFileName string                `json:"DumpFileName,omitempty"`
	MaxDumpSize  int64                 `json:"MaxDumpSize,omitempty"`
	DumpType     *WindowsCrashDumpType `json:"DumpType,omitempty"`
}
