// Autogenerated code; DO NOT EDIT.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Contact: containerplat-dev@microsoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

type WriteHardening string

// List of WriteHardening
const (
	WriteHardening_DEFAULT_             WriteHardening = "Default"
	WriteHardening_FLUSH                WriteHardening = "Flush"
	WriteHardening_FORCE_UNIT_ACCESS    WriteHardening = "ForceUnitAccess"
	WriteHardening_WRITE_CACHE_DISABLED WriteHardening = "WriteCacheDisabled"
	WriteHardening_UNKNOWN              WriteHardening = "Unknown"
)
