// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/Microsoft/hcsshim/internal/vm/hvlite/hvlite.proto

/*
	Package hvlite is a generated protocol buffer package.

	It is generated from these files:
		github.com/Microsoft/hcsshim/internal/vm/hvlite/hvlite.proto

	It has these top-level messages:
		VMConfig
		SCSIDisk
		CreateVMRequest
		CreateVMResponse
		StartVMRequest
		StartVMResponse
		StopVMRequest
		StopVMResponse
		WaitVMRequest
		WaitVMResponse
		AddSCSIDiskRequest
		AddSCSIDiskResponse
		HVSocketListenRequest
		HVSocketListenResponse
		AddNICRequest
		AddNICResponse
*/
package hvlite

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"

import context "golang.org/x/net/context"
import grpc "google.golang.org/grpc"

import strings "strings"
import reflect "reflect"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type SCSIDisk_DiskType int32

const (
	SCSIDisk_SCSI_DISK_TYPE_UNSPECIFIED SCSIDisk_DiskType = 0
	SCSIDisk_SCSI_DISK_TYPE_VHD1        SCSIDisk_DiskType = 1
	SCSIDisk_SCSI_DISK_TYPE_VHDX        SCSIDisk_DiskType = 2
)

var SCSIDisk_DiskType_name = map[int32]string{
	0: "SCSI_DISK_TYPE_UNSPECIFIED",
	1: "SCSI_DISK_TYPE_VHD1",
	2: "SCSI_DISK_TYPE_VHDX",
}
var SCSIDisk_DiskType_value = map[string]int32{
	"SCSI_DISK_TYPE_UNSPECIFIED": 0,
	"SCSI_DISK_TYPE_VHD1":        1,
	"SCSI_DISK_TYPE_VHDX":        2,
}

func (x SCSIDisk_DiskType) String() string {
	return proto.EnumName(SCSIDisk_DiskType_name, int32(x))
}
func (SCSIDisk_DiskType) EnumDescriptor() ([]byte, []int) { return fileDescriptorHvlite, []int{1, 0} }

type VMConfig struct {
	VmID           string      `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	MemoryMb       uint64      `protobuf:"varint,2,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`
	ProcessorCount uint64      `protobuf:"varint,3,opt,name=processor_count,json=processorCount,proto3" json:"processor_count,omitempty"`
	ScsiDisks      []*SCSIDisk `protobuf:"bytes,4,rep,name=scsi_disks,json=scsiDisks" json:"scsi_disks,omitempty"`
	KernelPath     string      `protobuf:"bytes,5,opt,name=kernel_path,json=kernelPath,proto3" json:"kernel_path,omitempty"`
	InitrdPath     string      `protobuf:"bytes,6,opt,name=initrd_path,json=initrdPath,proto3" json:"initrd_path,omitempty"`
	KernelArgs     string      `protobuf:"bytes,7,opt,name=kernel_args,json=kernelArgs,proto3" json:"kernel_args,omitempty"`
}

func (m *VMConfig) Reset()                    { *m = VMConfig{} }
func (*VMConfig) ProtoMessage()               {}
func (*VMConfig) Descriptor() ([]byte, []int) { return fileDescriptorHvlite, []int{0} }

func (m *VMConfig) GetVmID() string {
	if m != nil {
		return m.VmID
	}
	return ""
}

func (m *VMConfig) GetMemoryMb() uint64 {
	if m != nil {
		return m.MemoryMb
	}
	return 0
}

func (m *VMConfig) GetProcessorCount() uint64 {
	if m != nil {
		return m.ProcessorCount
	}
	return 0
}

func (m *VMConfig) GetScsiDisks() []*SCSIDisk {
	if m != nil {
		return m.ScsiDisks
	}
	return nil
}

func (m *VMConfig) GetKernelPath() string {
	if m != nil {
		return m.KernelPath
	}
	return ""
}

func (m *VMConfig) GetInitrdPath() string {
	if m != nil {
		return m.InitrdPath
	}
	return ""
}

func (m *VMConfig) GetKernelArgs() string {
	if m != nil {
		return m.KernelArgs
	}
	return ""
}

type SCSIDisk struct {
	Controller uint32            `protobuf:"varint,1,opt,name=controller,proto3" json:"controller,omitempty"`
	Lun        uint32            `protobuf:"varint,2,opt,name=lun,proto3" json:"lun,omitempty"`
	Path       string            `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Type       SCSIDisk_DiskType `protobuf:"varint,4,opt,name=type,proto3,enum=hvlite.SCSIDisk_DiskType" json:"type,omitempty"`
	ReadOnly   bool              `protobuf:"varint,5,opt,name=read_only,json=readOnly,proto3" json:"read_only,omitempty"`
}

func (m *SCSIDisk) Reset()                    { *m = SCSIDisk{} }
func (*SCSIDisk) ProtoMessage()               {}
func (*SCSIDisk) Descriptor() ([]byte, []int) { return fileDescriptorHvlite, []int{1} }

func (m *SCSIDisk) GetController() uint32 {
	if m != nil {
		return m.Controller
	}
	return 0
}

func (m *SCSIDisk) GetLun() uint32 {
	if m != nil {
		return m.Lun
	}
	return 0
}

func (m *SCSIDisk) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *SCSIDisk) GetType() SCSIDisk_DiskType {
	if m != nil {
		return m.Type
	}
	return SCSIDisk_SCSI_DISK_TYPE_UNSPECIFIED
}

func (m *SCSIDisk) GetReadOnly() bool {
	if m != nil {
		return m.ReadOnly
	}
	return false
}

type CreateVMRequest struct {
	Config *VMConfig `protobuf:"bytes,2,opt,name=config" json:"config,omitempty"`
}

func (m *CreateVMRequest) Reset()                    { *m = CreateVMRequest{} }
func (*CreateVMRequest) ProtoMessage()               {}
func (*CreateVMRequest) Descriptor() ([]byte, []int) { return fileDescriptorHvlite, []int{2} }

func (m *CreateVMRequest) GetConfig() *VMConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

type CreateVMResponse struct {
}

func (m *CreateVMResponse) Reset()                    { *m = CreateVMResponse{} }
func (*CreateVMResponse) ProtoMessage()               {}
func (*CreateVMResponse) Descriptor() ([]byte, []int) { return fileDescriptorHvlite, []int{3} }

type StartVMRequest struct {
}

func (m *StartVMRequest) Reset()                    { *m = StartVMRequest{} }
func (*StartVMRequest) ProtoMessage()               {}
func (*StartVMRequest) Descriptor() ([]byte, []int) { return fileDescriptorHvlite, []int{4} }

type StartVMResponse struct {
}

func (m *StartVMResponse) Reset()                    { *m = StartVMResponse{} }
func (*StartVMResponse) ProtoMessage()               {}
func (*StartVMResponse) Descriptor() ([]byte, []int) { return fileDescriptorHvlite, []int{5} }

type StopVMRequest struct {
}

func (m *StopVMRequest) Reset()                    { *m = StopVMRequest{} }
func (*StopVMRequest) ProtoMessage()               {}
func (*StopVMRequest) Descriptor() ([]byte, []int) { return fileDescriptorHvlite, []int{6} }

type StopVMResponse struct {
}

func (m *StopVMResponse) Reset()                    { *m = StopVMResponse{} }
func (*StopVMResponse) ProtoMessage()               {}
func (*StopVMResponse) Descriptor() ([]byte, []int) { return fileDescriptorHvlite, []int{7} }

type WaitVMRequest struct {
}

func (m *WaitVMRequest) Reset()                    { *m = WaitVMRequest{} }
func (*WaitVMRequest) ProtoMessage()               {}
func (*WaitVMRequest) Descriptor() ([]byte, []int) { return fileDescriptorHvlite, []int{8} }

type WaitVMResponse struct {
}

func (m *WaitVMResponse) Reset()                    { *m = WaitVMResponse{} }
func (*WaitVMResponse) ProtoMessage()               {}
func (*WaitVMResponse) Descriptor() ([]byte, []int) { return fileDescriptorHvlite, []int{9} }

type AddSCSIDiskRequest struct {
	Disk *SCSIDisk `protobuf:"bytes,1,opt,name=disk" json:"disk,omitempty"`
}

func (m *AddSCSIDiskRequest) Reset()                    { *m = AddSCSIDiskRequest{} }
func (*AddSCSIDiskRequest) ProtoMessage()               {}
func (*AddSCSIDiskRequest) Descriptor() ([]byte, []int) { return fileDescriptorHvlite, []int{10} }

func (m *AddSCSIDiskRequest) GetDisk() *SCSIDisk {
	if m != nil {
		return m.Disk
	}
	return nil
}

type AddSCSIDiskResponse struct {
}

func (m *AddSCSIDiskResponse) Reset()                    { *m = AddSCSIDiskResponse{} }
func (*AddSCSIDiskResponse) ProtoMessage()               {}
func (*AddSCSIDiskResponse) Descriptor() ([]byte, []int) { return fileDescriptorHvlite, []int{11} }

type HVSocketListenRequest struct {
	ServiceID    string `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	ListenerPath string `protobuf:"bytes,2,opt,name=listener_path,json=listenerPath,proto3" json:"listener_path,omitempty"`
}

func (m *HVSocketListenRequest) Reset()                    { *m = HVSocketListenRequest{} }
func (*HVSocketListenRequest) ProtoMessage()               {}
func (*HVSocketListenRequest) Descriptor() ([]byte, []int) { return fileDescriptorHvlite, []int{12} }

func (m *HVSocketListenRequest) GetServiceID() string {
	if m != nil {
		return m.ServiceID
	}
	return ""
}

func (m *HVSocketListenRequest) GetListenerPath() string {
	if m != nil {
		return m.ListenerPath
	}
	return ""
}

type HVSocketListenResponse struct {
}

func (m *HVSocketListenResponse) Reset()                    { *m = HVSocketListenResponse{} }
func (*HVSocketListenResponse) ProtoMessage()               {}
func (*HVSocketListenResponse) Descriptor() ([]byte, []int) { return fileDescriptorHvlite, []int{13} }

type AddNICRequest struct {
	NicID      string `protobuf:"bytes,1,opt,name=nic_id,json=nicId,proto3" json:"nic_id,omitempty"`
	EndpointID string `protobuf:"bytes,2,opt,name=endpoint_id,json=endpointId,proto3" json:"endpoint_id,omitempty"`
	Mac        string `protobuf:"bytes,3,opt,name=mac,proto3" json:"mac,omitempty"`
	PortID     string `protobuf:"bytes,4,opt,name=port_id,json=portId,proto3" json:"port_id,omitempty"`
}

func (m *AddNICRequest) Reset()                    { *m = AddNICRequest{} }
func (*AddNICRequest) ProtoMessage()               {}
func (*AddNICRequest) Descriptor() ([]byte, []int) { return fileDescriptorHvlite, []int{14} }

func (m *AddNICRequest) GetNicID() string {
	if m != nil {
		return m.NicID
	}
	return ""
}

func (m *AddNICRequest) GetEndpointID() string {
	if m != nil {
		return m.EndpointID
	}
	return ""
}

func (m *AddNICRequest) GetMac() string {
	if m != nil {
		return m.Mac
	}
	return ""
}

func (m *AddNICRequest) GetPortID() string {
	if m != nil {
		return m.PortID
	}
	return ""
}

type AddNICResponse struct {
}

func (m *AddNICResponse) Reset()                    { *m = AddNICResponse{} }
func (*AddNICResponse) ProtoMessage()               {}
func (*AddNICResponse) Descriptor() ([]byte, []int) { return fileDescriptorHvlite, []int{15} }

func init() {
	proto.RegisterType((*VMConfig)(nil), "hvlite.VMConfig")
	proto.RegisterType((*SCSIDisk)(nil), "hvlite.SCSIDisk")
	proto.RegisterType((*CreateVMRequest)(nil), "hvlite.CreateVMRequest")
	proto.RegisterType((*CreateVMResponse)(nil), "hvlite.CreateVMResponse")
	proto.RegisterType((*StartVMRequest)(nil), "hvlite.StartVMRequest")
	proto.RegisterType((*StartVMResponse)(nil), "hvlite.StartVMResponse")
	proto.RegisterType((*StopVMRequest)(nil), "hvlite.StopVMRequest")
	proto.RegisterType((*StopVMResponse)(nil), "hvlite.StopVMResponse")
	proto.RegisterType((*WaitVMRequest)(nil), "hvlite.WaitVMRequest")
	proto.RegisterType((*WaitVMResponse)(nil), "hvlite.WaitVMResponse")
	proto.RegisterType((*AddSCSIDiskRequest)(nil), "hvlite.AddSCSIDiskRequest")
	proto.RegisterType((*AddSCSIDiskResponse)(nil), "hvlite.AddSCSIDiskResponse")
	proto.RegisterType((*HVSocketListenRequest)(nil), "hvlite.HVSocketListenRequest")
	proto.RegisterType((*HVSocketListenResponse)(nil), "hvlite.HVSocketListenResponse")
	proto.RegisterType((*AddNICRequest)(nil), "hvlite.AddNICRequest")
	proto.RegisterType((*AddNICResponse)(nil), "hvlite.AddNICResponse")
	proto.RegisterEnum("hvlite.SCSIDisk_DiskType", SCSIDisk_DiskType_name, SCSIDisk_DiskType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for VM service

type VMClient interface {
	CreateVM(ctx context.Context, in *CreateVMRequest, opts ...grpc.CallOption) (*CreateVMResponse, error)
	StartVM(ctx context.Context, in *StartVMRequest, opts ...grpc.CallOption) (*StartVMResponse, error)
	StopVM(ctx context.Context, in *StopVMRequest, opts ...grpc.CallOption) (*StopVMResponse, error)
	WaitVM(ctx context.Context, in *WaitVMRequest, opts ...grpc.CallOption) (*WaitVMResponse, error)
	AddSCSIDisk(ctx context.Context, in *AddSCSIDiskRequest, opts ...grpc.CallOption) (*AddSCSIDiskResponse, error)
	HVSocketListen(ctx context.Context, in *HVSocketListenRequest, opts ...grpc.CallOption) (*HVSocketListenResponse, error)
	AddNIC(ctx context.Context, in *AddNICRequest, opts ...grpc.CallOption) (*AddNICResponse, error)
}

type vMClient struct {
	cc *grpc.ClientConn
}

func NewVMClient(cc *grpc.ClientConn) VMClient {
	return &vMClient{cc}
}

func (c *vMClient) CreateVM(ctx context.Context, in *CreateVMRequest, opts ...grpc.CallOption) (*CreateVMResponse, error) {
	out := new(CreateVMResponse)
	err := grpc.Invoke(ctx, "/hvlite.VM/CreateVM", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vMClient) StartVM(ctx context.Context, in *StartVMRequest, opts ...grpc.CallOption) (*StartVMResponse, error) {
	out := new(StartVMResponse)
	err := grpc.Invoke(ctx, "/hvlite.VM/StartVM", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vMClient) StopVM(ctx context.Context, in *StopVMRequest, opts ...grpc.CallOption) (*StopVMResponse, error) {
	out := new(StopVMResponse)
	err := grpc.Invoke(ctx, "/hvlite.VM/StopVM", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vMClient) WaitVM(ctx context.Context, in *WaitVMRequest, opts ...grpc.CallOption) (*WaitVMResponse, error) {
	out := new(WaitVMResponse)
	err := grpc.Invoke(ctx, "/hvlite.VM/WaitVM", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vMClient) AddSCSIDisk(ctx context.Context, in *AddSCSIDiskRequest, opts ...grpc.CallOption) (*AddSCSIDiskResponse, error) {
	out := new(AddSCSIDiskResponse)
	err := grpc.Invoke(ctx, "/hvlite.VM/AddSCSIDisk", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vMClient) HVSocketListen(ctx context.Context, in *HVSocketListenRequest, opts ...grpc.CallOption) (*HVSocketListenResponse, error) {
	out := new(HVSocketListenResponse)
	err := grpc.Invoke(ctx, "/hvlite.VM/HVSocketListen", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vMClient) AddNIC(ctx context.Context, in *AddNICRequest, opts ...grpc.CallOption) (*AddNICResponse, error) {
	out := new(AddNICResponse)
	err := grpc.Invoke(ctx, "/hvlite.VM/AddNIC", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for VM service

type VMServer interface {
	CreateVM(context.Context, *CreateVMRequest) (*CreateVMResponse, error)
	StartVM(context.Context, *StartVMRequest) (*StartVMResponse, error)
	StopVM(context.Context, *StopVMRequest) (*StopVMResponse, error)
	WaitVM(context.Context, *WaitVMRequest) (*WaitVMResponse, error)
	AddSCSIDisk(context.Context, *AddSCSIDiskRequest) (*AddSCSIDiskResponse, error)
	HVSocketListen(context.Context, *HVSocketListenRequest) (*HVSocketListenResponse, error)
	AddNIC(context.Context, *AddNICRequest) (*AddNICResponse, error)
}

func RegisterVMServer(s *grpc.Server, srv VMServer) {
	s.RegisterService(&_VM_serviceDesc, srv)
}

func _VM_CreateVM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateVMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMServer).CreateVM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hvlite.VM/CreateVM",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMServer).CreateVM(ctx, req.(*CreateVMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VM_StartVM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartVMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMServer).StartVM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hvlite.VM/StartVM",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMServer).StartVM(ctx, req.(*StartVMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VM_StopVM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopVMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMServer).StopVM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hvlite.VM/StopVM",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMServer).StopVM(ctx, req.(*StopVMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VM_WaitVM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WaitVMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMServer).WaitVM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hvlite.VM/WaitVM",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMServer).WaitVM(ctx, req.(*WaitVMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VM_AddSCSIDisk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddSCSIDiskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMServer).AddSCSIDisk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hvlite.VM/AddSCSIDisk",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMServer).AddSCSIDisk(ctx, req.(*AddSCSIDiskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VM_HVSocketListen_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HVSocketListenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMServer).HVSocketListen(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hvlite.VM/HVSocketListen",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMServer).HVSocketListen(ctx, req.(*HVSocketListenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VM_AddNIC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddNICRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMServer).AddNIC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hvlite.VM/AddNIC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMServer).AddNIC(ctx, req.(*AddNICRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _VM_serviceDesc = grpc.ServiceDesc{
	ServiceName: "hvlite.VM",
	HandlerType: (*VMServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateVM",
			Handler:    _VM_CreateVM_Handler,
		},
		{
			MethodName: "StartVM",
			Handler:    _VM_StartVM_Handler,
		},
		{
			MethodName: "StopVM",
			Handler:    _VM_StopVM_Handler,
		},
		{
			MethodName: "WaitVM",
			Handler:    _VM_WaitVM_Handler,
		},
		{
			MethodName: "AddSCSIDisk",
			Handler:    _VM_AddSCSIDisk_Handler,
		},
		{
			MethodName: "HVSocketListen",
			Handler:    _VM_HVSocketListen_Handler,
		},
		{
			MethodName: "AddNIC",
			Handler:    _VM_AddNIC_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/Microsoft/hcsshim/internal/vm/hvlite/hvlite.proto",
}

func (m *VMConfig) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *VMConfig) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.VmID) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintHvlite(dAtA, i, uint64(len(m.VmID)))
		i += copy(dAtA[i:], m.VmID)
	}
	if m.MemoryMb != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintHvlite(dAtA, i, uint64(m.MemoryMb))
	}
	if m.ProcessorCount != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintHvlite(dAtA, i, uint64(m.ProcessorCount))
	}
	if len(m.ScsiDisks) > 0 {
		for _, msg := range m.ScsiDisks {
			dAtA[i] = 0x22
			i++
			i = encodeVarintHvlite(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if len(m.KernelPath) > 0 {
		dAtA[i] = 0x2a
		i++
		i = encodeVarintHvlite(dAtA, i, uint64(len(m.KernelPath)))
		i += copy(dAtA[i:], m.KernelPath)
	}
	if len(m.InitrdPath) > 0 {
		dAtA[i] = 0x32
		i++
		i = encodeVarintHvlite(dAtA, i, uint64(len(m.InitrdPath)))
		i += copy(dAtA[i:], m.InitrdPath)
	}
	if len(m.KernelArgs) > 0 {
		dAtA[i] = 0x3a
		i++
		i = encodeVarintHvlite(dAtA, i, uint64(len(m.KernelArgs)))
		i += copy(dAtA[i:], m.KernelArgs)
	}
	return i, nil
}

func (m *SCSIDisk) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SCSIDisk) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Controller != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintHvlite(dAtA, i, uint64(m.Controller))
	}
	if m.Lun != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintHvlite(dAtA, i, uint64(m.Lun))
	}
	if len(m.Path) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintHvlite(dAtA, i, uint64(len(m.Path)))
		i += copy(dAtA[i:], m.Path)
	}
	if m.Type != 0 {
		dAtA[i] = 0x20
		i++
		i = encodeVarintHvlite(dAtA, i, uint64(m.Type))
	}
	if m.ReadOnly {
		dAtA[i] = 0x28
		i++
		if m.ReadOnly {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	return i, nil
}

func (m *CreateVMRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CreateVMRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Config != nil {
		dAtA[i] = 0x12
		i++
		i = encodeVarintHvlite(dAtA, i, uint64(m.Config.Size()))
		n1, err := m.Config.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n1
	}
	return i, nil
}

func (m *CreateVMResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CreateVMResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	return i, nil
}

func (m *StartVMRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StartVMRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	return i, nil
}

func (m *StartVMResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StartVMResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	return i, nil
}

func (m *StopVMRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StopVMRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	return i, nil
}

func (m *StopVMResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StopVMResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	return i, nil
}

func (m *WaitVMRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *WaitVMRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	return i, nil
}

func (m *WaitVMResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *WaitVMResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	return i, nil
}

func (m *AddSCSIDiskRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AddSCSIDiskRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Disk != nil {
		dAtA[i] = 0xa
		i++
		i = encodeVarintHvlite(dAtA, i, uint64(m.Disk.Size()))
		n2, err := m.Disk.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n2
	}
	return i, nil
}

func (m *AddSCSIDiskResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AddSCSIDiskResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	return i, nil
}

func (m *HVSocketListenRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *HVSocketListenRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.ServiceID) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintHvlite(dAtA, i, uint64(len(m.ServiceID)))
		i += copy(dAtA[i:], m.ServiceID)
	}
	if len(m.ListenerPath) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintHvlite(dAtA, i, uint64(len(m.ListenerPath)))
		i += copy(dAtA[i:], m.ListenerPath)
	}
	return i, nil
}

func (m *HVSocketListenResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *HVSocketListenResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	return i, nil
}

func (m *AddNICRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AddNICRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.NicID) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintHvlite(dAtA, i, uint64(len(m.NicID)))
		i += copy(dAtA[i:], m.NicID)
	}
	if len(m.EndpointID) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintHvlite(dAtA, i, uint64(len(m.EndpointID)))
		i += copy(dAtA[i:], m.EndpointID)
	}
	if len(m.Mac) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintHvlite(dAtA, i, uint64(len(m.Mac)))
		i += copy(dAtA[i:], m.Mac)
	}
	if len(m.PortID) > 0 {
		dAtA[i] = 0x22
		i++
		i = encodeVarintHvlite(dAtA, i, uint64(len(m.PortID)))
		i += copy(dAtA[i:], m.PortID)
	}
	return i, nil
}

func (m *AddNICResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AddNICResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	return i, nil
}

func encodeVarintHvlite(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *VMConfig) Size() (n int) {
	var l int
	_ = l
	l = len(m.VmID)
	if l > 0 {
		n += 1 + l + sovHvlite(uint64(l))
	}
	if m.MemoryMb != 0 {
		n += 1 + sovHvlite(uint64(m.MemoryMb))
	}
	if m.ProcessorCount != 0 {
		n += 1 + sovHvlite(uint64(m.ProcessorCount))
	}
	if len(m.ScsiDisks) > 0 {
		for _, e := range m.ScsiDisks {
			l = e.Size()
			n += 1 + l + sovHvlite(uint64(l))
		}
	}
	l = len(m.KernelPath)
	if l > 0 {
		n += 1 + l + sovHvlite(uint64(l))
	}
	l = len(m.InitrdPath)
	if l > 0 {
		n += 1 + l + sovHvlite(uint64(l))
	}
	l = len(m.KernelArgs)
	if l > 0 {
		n += 1 + l + sovHvlite(uint64(l))
	}
	return n
}

func (m *SCSIDisk) Size() (n int) {
	var l int
	_ = l
	if m.Controller != 0 {
		n += 1 + sovHvlite(uint64(m.Controller))
	}
	if m.Lun != 0 {
		n += 1 + sovHvlite(uint64(m.Lun))
	}
	l = len(m.Path)
	if l > 0 {
		n += 1 + l + sovHvlite(uint64(l))
	}
	if m.Type != 0 {
		n += 1 + sovHvlite(uint64(m.Type))
	}
	if m.ReadOnly {
		n += 2
	}
	return n
}

func (m *CreateVMRequest) Size() (n int) {
	var l int
	_ = l
	if m.Config != nil {
		l = m.Config.Size()
		n += 1 + l + sovHvlite(uint64(l))
	}
	return n
}

func (m *CreateVMResponse) Size() (n int) {
	var l int
	_ = l
	return n
}

func (m *StartVMRequest) Size() (n int) {
	var l int
	_ = l
	return n
}

func (m *StartVMResponse) Size() (n int) {
	var l int
	_ = l
	return n
}

func (m *StopVMRequest) Size() (n int) {
	var l int
	_ = l
	return n
}

func (m *StopVMResponse) Size() (n int) {
	var l int
	_ = l
	return n
}

func (m *WaitVMRequest) Size() (n int) {
	var l int
	_ = l
	return n
}

func (m *WaitVMResponse) Size() (n int) {
	var l int
	_ = l
	return n
}

func (m *AddSCSIDiskRequest) Size() (n int) {
	var l int
	_ = l
	if m.Disk != nil {
		l = m.Disk.Size()
		n += 1 + l + sovHvlite(uint64(l))
	}
	return n
}

func (m *AddSCSIDiskResponse) Size() (n int) {
	var l int
	_ = l
	return n
}

func (m *HVSocketListenRequest) Size() (n int) {
	var l int
	_ = l
	l = len(m.ServiceID)
	if l > 0 {
		n += 1 + l + sovHvlite(uint64(l))
	}
	l = len(m.ListenerPath)
	if l > 0 {
		n += 1 + l + sovHvlite(uint64(l))
	}
	return n
}

func (m *HVSocketListenResponse) Size() (n int) {
	var l int
	_ = l
	return n
}

func (m *AddNICRequest) Size() (n int) {
	var l int
	_ = l
	l = len(m.NicID)
	if l > 0 {
		n += 1 + l + sovHvlite(uint64(l))
	}
	l = len(m.EndpointID)
	if l > 0 {
		n += 1 + l + sovHvlite(uint64(l))
	}
	l = len(m.Mac)
	if l > 0 {
		n += 1 + l + sovHvlite(uint64(l))
	}
	l = len(m.PortID)
	if l > 0 {
		n += 1 + l + sovHvlite(uint64(l))
	}
	return n
}

func (m *AddNICResponse) Size() (n int) {
	var l int
	_ = l
	return n
}

func sovHvlite(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozHvlite(x uint64) (n int) {
	return sovHvlite(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *VMConfig) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&VMConfig{`,
		`VmID:` + fmt.Sprintf("%v", this.VmID) + `,`,
		`MemoryMb:` + fmt.Sprintf("%v", this.MemoryMb) + `,`,
		`ProcessorCount:` + fmt.Sprintf("%v", this.ProcessorCount) + `,`,
		`ScsiDisks:` + strings.Replace(fmt.Sprintf("%v", this.ScsiDisks), "SCSIDisk", "SCSIDisk", 1) + `,`,
		`KernelPath:` + fmt.Sprintf("%v", this.KernelPath) + `,`,
		`InitrdPath:` + fmt.Sprintf("%v", this.InitrdPath) + `,`,
		`KernelArgs:` + fmt.Sprintf("%v", this.KernelArgs) + `,`,
		`}`,
	}, "")
	return s
}
func (this *SCSIDisk) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&SCSIDisk{`,
		`Controller:` + fmt.Sprintf("%v", this.Controller) + `,`,
		`Lun:` + fmt.Sprintf("%v", this.Lun) + `,`,
		`Path:` + fmt.Sprintf("%v", this.Path) + `,`,
		`Type:` + fmt.Sprintf("%v", this.Type) + `,`,
		`ReadOnly:` + fmt.Sprintf("%v", this.ReadOnly) + `,`,
		`}`,
	}, "")
	return s
}
func (this *CreateVMRequest) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&CreateVMRequest{`,
		`Config:` + strings.Replace(fmt.Sprintf("%v", this.Config), "VMConfig", "VMConfig", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *CreateVMResponse) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&CreateVMResponse{`,
		`}`,
	}, "")
	return s
}
func (this *StartVMRequest) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&StartVMRequest{`,
		`}`,
	}, "")
	return s
}
func (this *StartVMResponse) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&StartVMResponse{`,
		`}`,
	}, "")
	return s
}
func (this *StopVMRequest) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&StopVMRequest{`,
		`}`,
	}, "")
	return s
}
func (this *StopVMResponse) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&StopVMResponse{`,
		`}`,
	}, "")
	return s
}
func (this *WaitVMRequest) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&WaitVMRequest{`,
		`}`,
	}, "")
	return s
}
func (this *WaitVMResponse) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&WaitVMResponse{`,
		`}`,
	}, "")
	return s
}
func (this *AddSCSIDiskRequest) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&AddSCSIDiskRequest{`,
		`Disk:` + strings.Replace(fmt.Sprintf("%v", this.Disk), "SCSIDisk", "SCSIDisk", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *AddSCSIDiskResponse) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&AddSCSIDiskResponse{`,
		`}`,
	}, "")
	return s
}
func (this *HVSocketListenRequest) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&HVSocketListenRequest{`,
		`ServiceID:` + fmt.Sprintf("%v", this.ServiceID) + `,`,
		`ListenerPath:` + fmt.Sprintf("%v", this.ListenerPath) + `,`,
		`}`,
	}, "")
	return s
}
func (this *HVSocketListenResponse) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&HVSocketListenResponse{`,
		`}`,
	}, "")
	return s
}
func (this *AddNICRequest) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&AddNICRequest{`,
		`NicID:` + fmt.Sprintf("%v", this.NicID) + `,`,
		`EndpointID:` + fmt.Sprintf("%v", this.EndpointID) + `,`,
		`Mac:` + fmt.Sprintf("%v", this.Mac) + `,`,
		`PortID:` + fmt.Sprintf("%v", this.PortID) + `,`,
		`}`,
	}, "")
	return s
}
func (this *AddNICResponse) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&AddNICResponse{`,
		`}`,
	}, "")
	return s
}
func valueToStringHvlite(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *VMConfig) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowHvlite
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: VMConfig: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: VMConfig: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VmID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHvlite
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthHvlite
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VmID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MemoryMb", wireType)
			}
			m.MemoryMb = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHvlite
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MemoryMb |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProcessorCount", wireType)
			}
			m.ProcessorCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHvlite
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ProcessorCount |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ScsiDisks", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHvlite
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthHvlite
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ScsiDisks = append(m.ScsiDisks, &SCSIDisk{})
			if err := m.ScsiDisks[len(m.ScsiDisks)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field KernelPath", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHvlite
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthHvlite
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.KernelPath = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InitrdPath", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHvlite
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthHvlite
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.InitrdPath = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field KernelArgs", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHvlite
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthHvlite
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.KernelArgs = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipHvlite(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthHvlite
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SCSIDisk) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowHvlite
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SCSIDisk: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SCSIDisk: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Controller", wireType)
			}
			m.Controller = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHvlite
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Controller |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Lun", wireType)
			}
			m.Lun = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHvlite
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Lun |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Path", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHvlite
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthHvlite
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Path = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			m.Type = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHvlite
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Type |= (SCSIDisk_DiskType(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReadOnly", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHvlite
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.ReadOnly = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipHvlite(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthHvlite
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CreateVMRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowHvlite
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CreateVMRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CreateVMRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Config", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHvlite
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthHvlite
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Config == nil {
				m.Config = &VMConfig{}
			}
			if err := m.Config.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipHvlite(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthHvlite
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CreateVMResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowHvlite
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CreateVMResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CreateVMResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipHvlite(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthHvlite
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *StartVMRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowHvlite
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StartVMRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StartVMRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipHvlite(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthHvlite
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *StartVMResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowHvlite
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StartVMResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StartVMResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipHvlite(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthHvlite
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *StopVMRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowHvlite
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StopVMRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StopVMRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipHvlite(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthHvlite
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *StopVMResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowHvlite
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StopVMResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StopVMResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipHvlite(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthHvlite
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *WaitVMRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowHvlite
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: WaitVMRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: WaitVMRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipHvlite(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthHvlite
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *WaitVMResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowHvlite
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: WaitVMResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: WaitVMResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipHvlite(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthHvlite
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AddSCSIDiskRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowHvlite
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AddSCSIDiskRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AddSCSIDiskRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Disk", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHvlite
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthHvlite
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Disk == nil {
				m.Disk = &SCSIDisk{}
			}
			if err := m.Disk.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipHvlite(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthHvlite
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AddSCSIDiskResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowHvlite
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AddSCSIDiskResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AddSCSIDiskResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipHvlite(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthHvlite
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *HVSocketListenRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowHvlite
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: HVSocketListenRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: HVSocketListenRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ServiceID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHvlite
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthHvlite
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ServiceID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ListenerPath", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHvlite
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthHvlite
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ListenerPath = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipHvlite(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthHvlite
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *HVSocketListenResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowHvlite
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: HVSocketListenResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: HVSocketListenResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipHvlite(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthHvlite
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AddNICRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowHvlite
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AddNICRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AddNICRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NicID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHvlite
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthHvlite
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NicID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EndpointID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHvlite
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthHvlite
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EndpointID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Mac", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHvlite
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthHvlite
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Mac = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PortID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHvlite
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthHvlite
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PortID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipHvlite(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthHvlite
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AddNICResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowHvlite
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AddNICResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AddNICResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipHvlite(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthHvlite
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipHvlite(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowHvlite
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowHvlite
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowHvlite
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthHvlite
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowHvlite
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipHvlite(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthHvlite = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowHvlite   = fmt.Errorf("proto: integer overflow")
)

func init() {
	proto.RegisterFile("github.com/Microsoft/hcsshim/internal/vm/hvlite/hvlite.proto", fileDescriptorHvlite)
}

var fileDescriptorHvlite = []byte{
	// 861 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x95, 0x4f, 0x6f, 0xe3, 0x44,
	0x18, 0xc6, 0xe3, 0x26, 0x4d, 0x93, 0xb7, 0x24, 0x0d, 0xb3, 0x6a, 0x1b, 0xb2, 0x5a, 0x27, 0xf2,
	0xae, 0x44, 0x0e, 0x6c, 0x23, 0xca, 0x09, 0x58, 0x09, 0xb5, 0x49, 0x51, 0x2d, 0x48, 0x29, 0xce,
	0x12, 0xfe, 0x08, 0xc9, 0x72, 0xec, 0x69, 0x32, 0xd4, 0xf6, 0x98, 0x99, 0x49, 0xa4, 0xdc, 0x90,
	0xf8, 0x02, 0x5c, 0xf9, 0x46, 0x7b, 0x84, 0x1b, 0xa7, 0x88, 0x35, 0xdf, 0x82, 0x13, 0x9a, 0xb1,
	0x1d, 0x27, 0x69, 0xb9, 0xb4, 0xe3, 0xe7, 0x7d, 0x9e, 0x77, 0xe6, 0xf5, 0xfc, 0x22, 0xc3, 0xab,
	0x29, 0x11, 0xb3, 0xf9, 0xe4, 0xcc, 0xa5, 0x41, 0x6f, 0x48, 0x5c, 0x46, 0x39, 0xbd, 0x13, 0xbd,
	0x99, 0xcb, 0xf9, 0x8c, 0x04, 0x3d, 0x12, 0x0a, 0xcc, 0x42, 0xc7, 0xef, 0x2d, 0x82, 0xde, 0x6c,
	0xe1, 0x13, 0x81, 0xd3, 0x7f, 0x67, 0x11, 0xa3, 0x82, 0xa2, 0x72, 0xf2, 0xd4, 0x7a, 0xb9, 0xd1,
	0x65, 0x4a, 0xa7, 0xb4, 0xa7, 0xca, 0x93, 0xf9, 0x9d, 0x7a, 0x52, 0x0f, 0x6a, 0x95, 0xc4, 0x8c,
	0x5f, 0xf7, 0xa0, 0x32, 0x1e, 0xf6, 0x69, 0x78, 0x47, 0xa6, 0xe8, 0x19, 0xec, 0x2f, 0x02, 0x9b,
	0x78, 0x4d, 0xad, 0xa3, 0x75, 0xab, 0x97, 0x95, 0x78, 0xd5, 0x2e, 0x8d, 0x03, 0x73, 0x60, 0x95,
	0x16, 0x81, 0xe9, 0xa1, 0xa7, 0x50, 0x0d, 0x70, 0x40, 0xd9, 0xd2, 0x0e, 0x26, 0xcd, 0xbd, 0x8e,
	0xd6, 0x2d, 0x59, 0x95, 0x44, 0x18, 0x4e, 0xd0, 0xfb, 0x70, 0x14, 0x31, 0xea, 0x62, 0xce, 0x29,
	0xb3, 0x5d, 0x3a, 0x0f, 0x45, 0xb3, 0xa8, 0x2c, 0xf5, 0xb5, 0xdc, 0x97, 0x2a, 0xea, 0x01, 0x70,
	0x97, 0x13, 0xdb, 0x23, 0xfc, 0x9e, 0x37, 0x4b, 0x9d, 0x62, 0xf7, 0xf0, 0xbc, 0x71, 0x96, 0xce,
	0x32, 0xea, 0x8f, 0xcc, 0x01, 0xe1, 0xf7, 0x56, 0x55, 0x7a, 0xe4, 0x8a, 0xa3, 0x36, 0x1c, 0xde,
	0x63, 0x16, 0x62, 0xdf, 0x8e, 0x1c, 0x31, 0x6b, 0xee, 0xcb, 0xb3, 0x59, 0x90, 0x48, 0xb7, 0x8e,
	0x98, 0x49, 0x03, 0x09, 0x89, 0x60, 0x5e, 0x62, 0x28, 0x27, 0x86, 0x44, 0xca, 0x0c, 0x69, 0x07,
	0x87, 0x4d, 0x79, 0xf3, 0x60, 0xb3, 0xc3, 0x05, 0x9b, 0x72, 0xe3, 0x5f, 0x0d, 0x2a, 0xd9, 0xd6,
	0x48, 0x07, 0x70, 0x69, 0x28, 0x18, 0xf5, 0x7d, 0xcc, 0xd4, 0xab, 0xa8, 0x59, 0x1b, 0x0a, 0x6a,
	0x40, 0xd1, 0x9f, 0x87, 0xea, 0x05, 0xd4, 0x2c, 0xb9, 0x44, 0x08, 0x4a, 0x6a, 0xe7, 0xa2, 0x6a,
	0xac, 0xd6, 0xe8, 0x25, 0x94, 0xc4, 0x32, 0xc2, 0xcd, 0x52, 0x47, 0xeb, 0xd6, 0xcf, 0xdf, 0xdb,
	0x1d, 0xf0, 0x4c, 0xfe, 0x79, 0xbd, 0x8c, 0xb0, 0xa5, 0x6c, 0xf2, 0xdd, 0x32, 0xec, 0x78, 0x36,
	0x0d, 0xfd, 0xa5, 0x1a, 0xb1, 0x62, 0x55, 0xa4, 0xf0, 0x55, 0xe8, 0x2f, 0x8d, 0x1f, 0xa1, 0x92,
	0xd9, 0x91, 0x0e, 0x2d, 0xd9, 0xc3, 0x1e, 0x98, 0xa3, 0x2f, 0xec, 0xd7, 0xdf, 0xdf, 0x5e, 0xd9,
	0xdf, 0xdc, 0x8c, 0x6e, 0xaf, 0xfa, 0xe6, 0xe7, 0xe6, 0xd5, 0xa0, 0x51, 0x40, 0xa7, 0xf0, 0x64,
	0xa7, 0x3e, 0xbe, 0x1e, 0x7c, 0xd8, 0xd0, 0x1e, 0x2f, 0x7c, 0xd7, 0xd8, 0x33, 0x3e, 0x85, 0xa3,
	0x3e, 0xc3, 0x8e, 0xc0, 0xe3, 0xa1, 0x85, 0x7f, 0x9e, 0x63, 0x2e, 0x50, 0x17, 0xca, 0xae, 0x42,
	0x42, 0x4d, 0xb9, 0x71, 0x3f, 0x19, 0x2a, 0x56, 0x5a, 0x37, 0x10, 0x34, 0xf2, 0x30, 0x8f, 0x68,
	0xc8, 0xb1, 0xd1, 0x80, 0xfa, 0x48, 0x38, 0x4c, 0xac, 0xfb, 0x19, 0xef, 0xc2, 0xd1, 0x5a, 0x49,
	0x4d, 0x47, 0x50, 0x1b, 0x09, 0x1a, 0xe5, 0x1e, 0x95, 0x4a, 0x84, 0xdc, 0xf2, 0xad, 0x43, 0xc4,
	0x96, 0x25, 0x13, 0x52, 0xcb, 0x27, 0x80, 0x2e, 0x3c, 0x6f, 0x4d, 0x4d, 0x7a, 0xfc, 0x17, 0x50,
	0x92, 0x74, 0xa9, 0xbb, 0x7b, 0x0c, 0x2e, 0x55, 0x35, 0x8e, 0xe1, 0xc9, 0x56, 0x36, 0x6d, 0xf9,
	0x13, 0x1c, 0x5f, 0x8f, 0x47, 0xd4, 0xbd, 0xc7, 0xe2, 0x4b, 0xc2, 0x05, 0x0e, 0xb3, 0xae, 0x1f,
	0x00, 0x70, 0xcc, 0x16, 0xc4, 0xc5, 0xf9, 0x4f, 0xa4, 0x16, 0xaf, 0xda, 0xd5, 0x51, 0xa2, 0x9a,
	0x03, 0xab, 0x9a, 0x1a, 0x4c, 0x0f, 0x3d, 0x87, 0x9a, 0xaf, 0xe2, 0x98, 0x25, 0x58, 0xee, 0x29,
	0x38, 0xde, 0xc9, 0x44, 0x09, 0xa6, 0xd1, 0x84, 0x93, 0xdd, 0xbd, 0xd2, 0x53, 0xfc, 0xae, 0x41,
	0xed, 0xc2, 0xf3, 0x6e, 0xcc, 0x7e, 0xb6, 0x7d, 0x07, 0xca, 0x21, 0x71, 0xf3, 0xad, 0xab, 0xf1,
	0xaa, 0xbd, 0x7f, 0x43, 0x5c, 0x73, 0x60, 0xed, 0x87, 0xc4, 0x35, 0x3d, 0xd4, 0x83, 0x43, 0x1c,
	0x7a, 0x11, 0x25, 0xa1, 0x90, 0x36, 0xb5, 0xe1, 0x65, 0x3d, 0x5e, 0xb5, 0xe1, 0x2a, 0x95, 0xcd,
	0x81, 0x05, 0x99, 0xc5, 0xf4, 0x24, 0xc9, 0x81, 0xe3, 0xa6, 0xd8, 0xca, 0x25, 0x7a, 0x0e, 0x07,
	0x11, 0x65, 0x2a, 0x5e, 0x52, 0x71, 0x88, 0x57, 0xed, 0xf2, 0x2d, 0x65, 0x32, 0x5a, 0x96, 0x25,
	0xd3, 0x93, 0xd7, 0x90, 0x1d, 0x2d, 0x39, 0xed, 0xf9, 0x9f, 0x45, 0xd8, 0x1b, 0x0f, 0xd1, 0x67,
	0x50, 0xc9, 0x60, 0x40, 0xa7, 0xd9, 0x5b, 0xdf, 0x61, 0xab, 0xd5, 0x7c, 0x58, 0x48, 0x67, 0x2e,
	0xa0, 0x57, 0x70, 0x90, 0x72, 0x82, 0x4e, 0xd6, 0xb7, 0xb6, 0x85, 0x52, 0xeb, 0xf4, 0x81, 0xbe,
	0x4e, 0x7f, 0x0c, 0xe5, 0x84, 0x20, 0x74, 0x9c, 0x9b, 0x36, 0x10, 0x6b, 0x9d, 0xec, 0xca, 0x9b,
	0xd1, 0x84, 0xac, 0x3c, 0xba, 0x85, 0x5e, 0x1e, 0xdd, 0x01, 0xb0, 0x80, 0xae, 0xe1, 0x70, 0x03,
	0x23, 0xd4, 0xca, 0x8c, 0x0f, 0xb9, 0x6c, 0x3d, 0x7d, 0xb4, 0xb6, 0xee, 0xf4, 0x35, 0xd4, 0xb7,
	0x69, 0x40, 0xcf, 0xb2, 0xc0, 0xa3, 0x44, 0xb6, 0xf4, 0xff, 0x2b, 0x6f, 0xce, 0x95, 0x5c, 0x55,
	0x3e, 0xd7, 0x16, 0x55, 0xf9, 0x5c, 0xdb, 0x37, 0x6a, 0x14, 0x2e, 0x5f, 0xbc, 0x79, 0xab, 0x6b,
	0x7f, 0xbd, 0xd5, 0x0b, 0xbf, 0xc4, 0xba, 0xf6, 0x26, 0xd6, 0xb5, 0x3f, 0x62, 0x5d, 0xfb, 0x3b,
	0xd6, 0xb5, 0xdf, 0xfe, 0xd1, 0x0b, 0x3f, 0xa4, 0x9f, 0x9b, 0x49, 0x59, 0x7d, 0x46, 0x3e, 0xfa,
	0x2f, 0x00, 0x00, 0xff, 0xff, 0x16, 0xf4, 0x87, 0x88, 0xbd, 0x06, 0x00, 0x00,
}
